export default {
  isoAlpha2: null,
  isoAlpha3: null,
  numericCountryCode: null,
  country: null,
  city: null,
  short: null,
  long: null,
  idName: null,
  main: null,
  center: null,
  latitude: null,
  longitude: null,
  info: null,
  broken: false,
  download: null,
  format: null,
  filename: null,
  gdal_options: null,
  license: null,
  email: null,
  contact: null,
  // crosswalk: null,
};
