export default {
  country: null,
  city: null,
  short: null,
  long: null,
  id: null,
  id_city_name: null,
  primary: null,
  center: null,
  latitude: null,
  longitude: null,
  info: null,
  srs: null,
  download: null,
  format: null,
  filename: null,
  format: null,
  gdal_options: null,
  license: null,
  email: null,
  contact: null,
  // crosswalk: null,
};
