export default [
  {
    country: "Argentina",
    city: "Buenos Aires",
    short: "Buenos Aires",
    long: "Buenos Aires",
    id: "buenos_aires",
    id_city_name: "buenos_aires",
    primary: "buenos_aires",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.buenosaires.gob.ar/dataset/arbolado-espacios-verdes",
    srs: null,
    download:
      "http://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-en-espacios-verdes/arbolado-en-espacios-verdes.csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "id_arbol",
      height: "altura_tot",
      dbh: "diametre",
      common: "nombre_com",
      scientific: "nombre_cie",
      family: "nombre_fam",
    },
  },
  {
    country: "Argentina",
    city: "Buenos Aires2",
    short: "Buenos Aires2",
    long: "Buenos Aires2",
    id: "buenos_aires2",
    id_city_name: "buenos_aires2",
    primary: "buenos_aires",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.buenosaires.gob.ar/dataset/arbolado-publico-lineal",
    srs: null,
    download:
      "http://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-publico-lineal/arbolado-publico-lineal-2017-2018.geojson",
    format: "geojson",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "nro_registro",
      scientific: "nombre_cientifico",
      dbh: "diametro_altura_pecho",
      height: "altura_arbol",
    },
  },
];
