const country = [
  {
    isoAlpha2: 'AR',
    isoAlpha3: 'ARG',
    numericCountryCode: '032',
    country: 'Argentina',
  }
]

export default [
  {
    isoAlpha2: 'AR',
    isoAlpha3: 'ARG',
    numericCountryCode: '032',
    country: "Argentina",
    city: "Buenos Aires",
    short: "Buenos Aires",
    long: "Buenos Aires",
    idSourceName: "buenos_aires",
    main: "buenos_aires",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.buenosaires.gob.ar/dataset/arbolado-espacios-verdes",
    broken: false,
    download:
      "http://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-en-espacios-verdes/arbolado-en-espacios-verdes.csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "id_arbol",
      height: "altura_tot",
      dbh: "diametre",
      common: "nombre_com",
      scientific: "nombre_cie",
      family: "nombre_fam",
    },
  },
  {
    isoAlpha2: 'AR',
    isoAlpha3: 'ARG',
    numericCountryCode: '032',
    country: "Argentina",
    city: "Buenos Aires2",
    short: "Buenos Aires2",
    long: "Buenos Aires2",
    idSourceName: "buenos_aires2",
    main: "buenos_aires",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.buenosaires.gob.ar/dataset/arbolado-publico-lineal",
    broken: false,
    download:
      "http://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-publico-lineal/arbolado-publico-lineal-2017-2018.geojson",
    format: "geojson",
    filename: "buenos_aires2.geojson",  
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "nro_registro",
      scientific: "nombre_cientifico",
      dbh: "diametro_altura_pecho",
      height: "altura_arbol",
    },
  },
];
