<<<<<<< HEAD
module.exports = [
    {
        id:'antwerpen_be',
        country: 'Belgium',
        short: 'Antwerp',
        long: '',
        download: 'https://opendata.arcgis.com/datasets/0293af55ca454b44ba789ee14c82543a_676.zip',
        info:'https://portaal-stadantwerpen.opendata.arcgis.com/datasets/boom/data',
        crosswalk: {
            scientific: 'LATBOOMSOO',
            dbh: 'STAMOMTREK',
            ref: 'ANTW_ID',

        }
    },
    {
        id:'wallonie_bruxelles_be',
        short: 'Wallonie-Bruxelles',
        long: '',
        download: 'https://www.odwb.be/explore/dataset/arbustum/download/?format=shp',
        info:'https://www.odwb.be/explore/dataset/arbustum/information/',
        crosswalk: {
        },
        license: '',
    },
    {
        id:'roosendaal_be',
        short: 'Roosendaal',
        long: 'Gemeente Roosendaal',
        download: 'https://opendata.arcgis.com/datasets/f97b4a30ac914a73aa7552a96f0ae82d_0.zip',
        info:'https://opendata.roosendaal.nl/datasets/gbi-boom-public',
        crosswalk: {
        },
        license: '',
    },
    {
        id:'gent_be',
        short: 'Gent',
        long: 'Stad Gent',
        download: 'https://datatank.stad.gent/4/milieuennatuur/bomeninventaris.json',
        info:'https://datatank.stad.gent/4/milieuennatuur/bomeninventaris',
        srs: 'EPSG:3857', // why....
        crosswalk: {
        },
        license: 'https://overheid.vlaanderen.be/sites/default/files/documenten/ict-egov/licenties/hergebruik/modellicentie_gratis_hergebruik_v1_0.html',
    },
].map(s => ({...s, country: 'Belgium' }));
=======
export default [
  {
    country: "Belgium",
    city: "Antwerp",
    short: "Antwerp",
    long: "Antwerp",
    id: "antwerpen_be",
    id_city_name: "antwerpen_be",
    primary: "antwerpen_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://portaal-stadantwerpen.opendata.arcgis.com/datasets/boom/data",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/0293af55ca454b44ba789ee14c82543a_676.zip",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { scientific: "LATBOOMSOO", dbh: "STAMOMTREK", ref: "ANTW_ID" },
  },
  {
    country: "Belgium",
    city: "Wallonie-Bruxelles",
    short: "Wallonie-Bruxelles",
    long: "Wallonie-Bruxelles",
    id: "wallonie_bruxelles_be",
    id_city_name: "wallonie_bruxelles_be",
    primary: "wallonie_bruxelles_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.odwb.be/explore/dataset/arbustum/information/",
    srs: null,
    brokenDownload: false,
    download:
      "https://www.odwb.be/explore/dataset/arbustum/download/?format=shp",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
  {
    country: "Belgium",
    city: "Roosendaal",
    short: "Roosendaal",
    long: "Gemeente Roosendaal",
    id: "roosendaal_be",
    id_city_name: "roosendaal_be",
    primary: "roosendaal_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://opendata.roosendaal.nl/datasets/gbi-boom-public",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/f97b4a30ac914a73aa7552a96f0ae82d_0.zip",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
  {
    country: "Belgium",
    city: "Gent",
    short: "Gent",
    long: "Stad Gent",
    id: "gent_be",
    id_city_name: "gent_be",
    primary: "gent_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://datatank.stad.gent/4/milieuennatuur/bomeninventaris",
    srs: null,
    brokenDownload: true,
    download:
      "https://datatank.stad.gent/4/milieuennatuur/bomeninventaris.json",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
];
>>>>>>> f6f6864a5e38638b7899216b85e7d14a9ed24c56
