const country = [
  {
    isoAlpha2: 'BE',
    isoAlpha3: 'BEL',
    numericCountryCode: '056',
    country: "Belgium",
  }
]

export default [
  {
    isoAlpha2: 'BE',
    isoAlpha3: 'BEL',
    numericCountryCode: '056',
    country: "Belgium",
    city: "Antwerp",
    short: "Antwerp",
    long: "Antwerp",
    idName: "antwerpen_be",
    main: "antwerpen_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://portaal-stadantwerpen.opendata.arcgis.com/datasets/boom/data",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/0293af55ca454b44ba789ee14c82543a_676.zip",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { scientific: "LATBOOMSOO", dbh: "STAMOMTREK", idReference: "ANTW_ID" },
  },
  {
    isoAlpha2: 'BE',
    isoAlpha3: 'BEL',
    numericCountryCode: '056',
    country: "Belgium",
    city: "Wallonie-Bruxelles",
    short: "Wallonie-Bruxelles",
    long: "Wallonie-Bruxelles",
    idName: "wallonie_bruxelles_be",
    main: "wallonie_bruxelles_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.odwb.be/explore/dataset/arbustum/information/",
    broken: false,
    download:
      "https://www.odwb.be/explore/dataset/arbustum/download/?format=shp",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
  {
    isoAlpha2: 'BE',
    isoAlpha3: 'BEL',
    numericCountryCode: '056',
    country: "Belgium",
    city: "Roosendaal",
    short: "Roosendaal",
    long: "Gemeente Roosendaal",
    idName: "roosendaal_be",
    main: "roosendaal_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://opendata.roosendaal.nl/datasets/gbi-boom-public",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/f97b4a30ac914a73aa7552a96f0ae82d_0.zip",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
  {
    isoAlpha2: 'BE',
    isoAlpha3: 'BEL',
    numericCountryCode: '056',
    country: "Belgium",
    city: "Gent",
    short: "Gent",
    long: "Stad Gent",
    idName: "gent_be",
    main: "gent_be",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://datatank.stad.gent/4/milieuennatuur/bomeninventaris",
    broken: true,
    download:
      "https://datatank.stad.gent/4/milieuennatuur/bomeninventaris.json",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
];
