const country = [
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
  }
]

export default [
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Paris",
    short: "Paris",
    long: "Paris",
    idSourceName: "paris",
    main: "paris",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://data.iledefrance.fr//explore/dataset/les-arbres/download?format=geojson&amp;timezone=Europe/Berlin&amp;use_labels_for_header=false",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "idemplacement",
      common: "libellefrancais",
      genus: "genre",
      species: "espece",
      variety: "varieteoucultivar",
      dbh: "(x) => (Number(x.circonferenceencm) / 3.14159) * 2",
      age: "stadedeveloppement",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Lyon",
    short: "Lyon",
    long: "Lyon",
    idSourceName: "lyon",
    main: "lyon",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://download.data.grandlyon.com/ws/grandlyon/abr_arbres_alignement.abrarbre.shp?srsname=EPSG:4326",
    format: "zip",
    filename: "abr_arbres_alignement.abrarbre.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "essence",
      variety: "variete",
      genus: "genre",
      species: "espece",
      location: "localisati",
      planted: "anneeplant",
      idReference: "identifian",
      common: "essencefra",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Bordeaux",
    short: "Bordeaux",
    long: "Bordeaux",
    idSourceName: "bordeaux",
    main: "bordeaux",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://opendata.bordeaux-metropole.fr/explore/dataset/bor_arbres/information/",
    broken: false,
    download:
      "https://opendata.bordeaux-metropole.fr/explore/dataset/bor_arbres/download/?format=geojson&lang=en",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "nom",
      updated: "mdate",
      dbh: "diametre",
      height: "hauteur",
      family: "famille",
      variety: "variete",
      location: "typo_espace",
      health: "statut",
      planted: "tranche_age",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Nice",
    short: "Nice",
    long: "Nice",
    idSourceName: "nice",
    main: "nice",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://trouver.datasud.fr/dataset/sync149f50a-cartographie-des-arbres-communaux",
    broken: false,
    download:
      "http://opendata.nicecotedazur.org/data/storage/f/2019-07-22T07%3A41%3A29.958Z/ev-arbre-opendata-2019.geojson",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { idReference: "idENT" },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Grenoble",
    short: "Grenoble",
    long: "Grenoble",
    idSourceName: "grenoble",
    main: "grenoble",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://data.metropolegrenoble.fr/ckan/dataset/les-arbres-de-grenoble",
    broken: true,
    download:
      "https://entrepot.metropolegrenoble.fr/opendata/38185-GRE/EspacePublic/json/ARBRES_TERRITOIRE_VDG_EPSG4326.json",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "BIEN_REFERENCE",
      genus: "GENRE_BOTA",
      species: "ESPECE",
      variety: "VARIETE",
      age: "STADEDEDEVELOPPEMENT",
      note: "REMARQUES",
      planted: "ANNEDEPLANTATION",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Montpellier",
    short: "Montpellier",
    long: "Montpellier",
    idSourceName: "montpellier",
    main: "montpellier",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.montpellier3m.fr/dataset/arbres-dalignement-de-montpellier",
    broken: false,
    download:
      "https://data.montpellier3m.fr/sites/default/files/ressources/MMM_MTP_ArbresAlign.zip",
    format: "zip",
    filename: "MMM_MTP_ArbresAlign.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "idarbre",
      scientific: "nom_latin",
      common: "nom_commun",
      planted: "plantation",
      updated: "releva",
      crown: "couronnem",
      height: "hauteurm",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Grand Paris Seine Ouest",
    short: "Grand Paris Seine Ouest",
    long: "Grand Paris Seine Ouest",
    idSourceName: "grand_paris_seine_ouest",
    main: "grand_paris_seine_ouest",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/arbres-2/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/a10c7776-afa5-4b8a-8050-081788818b55",
    format: "zip",
    filename: "arbres-v2.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "genespvar",
      height: "hauteur",
      planted: "an_plant",
      idReference: "id_plant",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Agen",
    short: "Agen",
    long: "Agen",
    idSourceName: "agen",
    main: "agen",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/fededc1c-6e42-4a6d-9469-849fd956fbfe",
    format: "zip",
    filename: "Arbres.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "id_ponctue",
      common: "espece_arb",
      scientific: "nom_latin",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Saint Quentinois",
    short: "Saint Quentinois",
    long: "Agglomération du Saint Quentinois",
    idSourceName: "saint_quentinois",
    main: "saint_quentinois",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/c6000378-1f3c-4c0c-8f62-9a5b72dc7a85",
    format: "zip",
    filename: "ARBRES.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "nomlatin",
      common: "nomfrancai",
      updated: "EditDate",
      age: "fk_stadede",
      dbh: "tronc_diam",
      height: "haut_tot",
      idReference: "id_arbre",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Metz",
    short: "Metz",
    long: "Metz",
    idSourceName: "metz",
    main: "metz",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/3aa28eaa-9ee4-49ff-bb73-74c21d14268d",
    format: "zip",
    filename: "vrd_esv_arb.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: "diametre",
      scientific: "nom_espece",
      note: "observatio",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Seine-Saint-Denis",
    short: "Seine-Saint-Denis",
    long: "Seine-Saint-Denis",
    idSourceName: "seine_saint_denis",
    main: "seine_saint_denis",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/c631e78d-4d15-44eb-a40d-cd593f0e1bed",
    format: "zip",
    filename: "fr-dpt93-1646.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      height: "hauteur",
      scientific: "essence",
      age: "stade_dvlp",
      dbh: "(x) => `dbh: ${x.circonfere}`",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Versailles",
    short: "Versailles",
    long: "Versailles",
    idSourceName: "versailles",
    main: "versailles",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "http://www-cavgp.opendata.arcgis.com/datasets/c41b83ccc9c14c608be3a136da9244c6_2.geojson",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { scientific: "ESPECE", common: "FRANCAIS" },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Nevers",
    short: "Nevers",
    long: "Ville de Nevers",
    idSourceName: "nevers",
    main: "nevers",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/dbdc2068-ee22-474d-8a42-261554482a4f",
    format: "zip",
    filename: "ARBRE_ALIGNEMENT.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { scientific: "espece" },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Toulouse",
    short: "Toulouse",
    long: "Toulouse Métropole",
    idSourceName: "toulouse",
    main: "toulouse",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/arbres-dalignement-toulouse/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/b5b275e5-ef20-43c4-ad3f-5604c67a75a3",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { idReference: "id", common: "patrimoine" },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Orléans",
    short: "Orléans",
    long: "Ville d'Orléans",
    idSourceName: "orleans",
    main: "orleans",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/arbres-ville-dorleans/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/804b8b61-9f8f-4a0d-8524-35ea5d6e265f",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "id_arbre",
      genus: '(x) => String(x.genre).replace(/ \\?/, "")',
      species: '(x) => String(x.species).replace(/ \\?/, "")',
      variety: "variete",
      planted: "date_plant",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Saint-Egrève",
    short: "Saint-Egrève",
    long: "Ville de Saint-Egrève",
    idSourceName: "saint_egreve",
    main: "saint_egreve",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/les-arbres-de-saint-egreve/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/2bda9508-27e5-4de6-aba3-fdb0d9059a22",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      genus: "genre",
      species: "espece",
      planted: "anne_plan",
      common: "essence",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Bayonne",
    short: "Bayonne",
    long: "Ville de Bayonne",
    idSourceName: "bayonne",
    main: "bayonne",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/arbres-dalignement-bayonne/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/e99bddd1-384b-4954-9f4f-483bb0fcaef0",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      genus: "genre",
      species: "espece",
      height: "hauteur",
      common: "vernaculai",
      variety: "variete",
      planted: "anne_plan",
      scientific: "gev",
      dbh: "circonf",
      age: "agechrono",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Issy-les-Moulineaux",
    short: "Issy-les-Moulineaux",
    long: "Ville d'Issy-les-Moulineaux",
    idSourceName: "issy",
    main: "issy",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/r/578636b3-e9ca-4aa7-b298-e69fd0f3acc9",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/578636b3-e9ca-4aa7-b298-e69fd0f3acc9",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "essence_sci",
      common: "essence_com",
      dbh: "circonferen",
      height: "hauteur",
      age: "classe_age",
      health: "statut_emp",
      updated: "date_maj",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Rennes",
    short: "Rennes",
    long: "Rennes Métropole",
    idSourceName: "rennes1",
    main: "rennes1",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/arbres-dornement-des-espaces-verts-de-la-ville-de-rennes-1/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/85d25eb0-b34e-4559-884d-ac052e62c620",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      genus: "genre",
      species: "espece",
      planted: "date_plant",
      variety: "variete",
      dbh: "circonfere",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Rennes",
    short: "Rennes",
    long: "Rennes Métropole",
    idSourceName: "rennes2",
    main: "rennes1",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/arbres-dalignement-en-accompagnement-de-voirie-sur-la-ville-de-rennes-1/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/c9cf6518-267c-4aa4-bdbe-d1602f78b07f",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "numero",
      planted: "date_plant",
      health: "etat",
      genus: "genre",
      species: "espece",
      variety: "variete",
      dbh: "circonfere",
      height: "hauteur",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Mulhouse",
    short: "Mulhouse",
    long: "Mulhouse Alsace Agglomération",
    idSourceName: "mulhouse",
    main: "mulhouse",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.data.gouv.fr/fr/datasets/caracteristiques-des-arbres-dalignements-geres-par-la-ville-de-mulhouse/",
    broken: true,
    download:
      "https://www.data.gouv.fr/fr/datasets/r/3c47ef6b-10ea-4723-81b9-a3c0b99e9550",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "libelle_es",
      planted: "date_plant",
      common: "com_nom",
      idReference: "obj_ident",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Divonne-les-Bains",
    short: "Divonne-les-Bains",
    long: "Divonne-les-Bains",
    idSourceName: "divonne_les_bains_fr",
    main: "divonne_les_bains_fr",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.datara.gouv.fr/geonetwork/srv/fre/catalog.search#/metadata/b18070b7-4349-4fd5-8e56-1dc48c3eb03a",
    broken: false,
    download:
      "https://telecarto.datara.gouv.fr/DOWNLOAD/Telechargement_1584570708_1630.zip",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      genus: '(x) => x.genre.replace("spp.", "")',
      species: "espece",
      height: "classe_hau",
      dbh: "classe_cir",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Bretagne",
    short: "Bretagne",
    long: "La Région Bretagne",
    idSourceName: "bretagne_fr",
    main: "bretagne_fr",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.bretagne.bzh/explore/dataset/patrimoine-arbore-ponctuel-des-voies-navigables-appartenant-a-la-region-bretagne/export/",
    broken: false,
    download:
      "https://data.bretagne.bzh/explore/dataset/patrimoine-arbore-ponctuel-des-voies-navigables-appartenant-a-la-region-bretagne/download/?format=shp&timezone=Australia/Sydney&lang=fr",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "gml_id",
      common: "essence",
      height: "hauteur",
      dbh: "diametre",
      health: "etat_genera",
      note: "remarque",
    },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Guingamp",
    short: "Guingamp",
    long: "Ville de Guingamp",
    idSourceName: "guingamp_fr",
    main: "guingamp_fr",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://datarmor.cotesdarmor.fr/data-presentation-ux/#/cg22/datasets/Arbres_Guingamp/views/grid?main-bg-color=@046D8B&main-font-color=@fff",
    broken: true,
    broken_reason: "No common field",
    download:
      "https://datarmor.cotesdarmor.fr:443/dataserver/cg22/data/Arbres_Guingamp?&$format=csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { genus: "Genre", species: "Espce", variety: "Varit" },
  },
  {
    isoAlpha2: 'FR',
    isoAlpha3: 'FRA',
    numericCountryCode: '250',
    country: "France",
    city: "Grand Paris Sud",
    short: "Grand Paris Sud",
    long: "Grand Paris Sud",
    idSourceName: "paris_sud_fr",
    main: "paris_sud_fr",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.grandparissud.fr/explore/dataset/patrimoine-arbore/export/",
    broken: false,
    download:
      "https://data.grandparissud.fr/explore/dataset/patrimoine-arbore/download/?format=shp&timezone=Australia/Sydney&lang=fr",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      location: "categorie",
      owner: "gestionnai",
      common: "(x) => `${x.ess_fcais} ${x.espe_fcais}`",
      scientific: "ess_latin",
      age: "classe_age",
      health: "vigeur_cr",
      updated: "anne_expe",
      idReference: "identifian",
    },
  },
];
