const country = [
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
  }
]

export default [
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Halle",
    short: "Halle",
    long: "Halle (Saale)",
    idSourceName: "halle",
    main: "halle",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.halle.de/de/Verwaltung/Online-Angebote/Offene-Verwaltungsdaten/Mit-Kartenbezug/index.aspx?ID=f2087a53-2c10-f7c5-4dba-9ad5112a90cb",
    broken: false,
    download:
      "https://www.halle.de/pushOD.aspx?FileName=f2087a53-2c10-f7c5-4dba-9ad5112a90cb_shp.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      planted: "pflanzjahr",
      crown: "krone_m",
      height: "hoehe_m",
      idReference: "baum_nr",
      scientific: "art_botan",
      common: "art_deut",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Netherlands",
    city: "Utrecht",
    short: "Utrecht",
    long: "Utrecht",
    idSourceName: "utrecht",
    main: "utrecht",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://ckan.dataplatform.nl/dataset/bomenkaart/resource/2d6893b4-d56d-4865-b6cc-0bda42e547f5",
    broken: false,
    download:
      "https://ckan.dataplatform.nl/datastore/dump/2d6893b4-d56d-4865-b6cc-0bda42e547f5?bom=True",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Naam_Wet",
      common: "Naam_NL",
      planted: "Plantjaar",
      idReference: "Boomnr",
      owner: "Eigenaar",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Leipzig",
    short: "Leipzig",
    long: "Leipzig",
    idSourceName: "leipzig",
    main: "leipzig",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://hub.arcgis.com/datasets/esri-de-content::stra%C3%9Fenbaumkataster-leipzig",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/918dfaa87b754c4384ddcf869cfd6dc6_0.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Baumart_wi",
      common: "Baumart_de",
      planted: "Pflanzjahr",
      idReference: "STANDORTNR",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Bonn",
    short: "Bonn",
    long: "Bonn",
    idSourceName: "bonn",
    main: "bonn",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://opendata.gis.ms.gov/datasets/esri-de-content::baumkataster-bonn",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/f8f130c1dd4e4ea9b5fe1f2385673cab_0.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "baum_id",
      scientific: "lateinisch",
      common: "deutscher_",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Köln",
    short: "Köln",
    long: "Stadt Köln",
    idSourceName: "koeln",
    main: "koeln",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://offenedaten-koeln.de/dataset/baumkataster-koeln",
    broken: false,
    download:
      "https://offenedaten-koeln.de/sites/default/files/Bestand_Einzelbaeume_Koeln_0.csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "Baum-Nr.",
      crown: "KRONE",
      height: "HöHE",
      age: "AlterSchätzung",
      genus: "Gattung",
      species: "Art",
      common: "DeutscherN",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Berlin",
    short: "Berlin",
    long: "Berlin",
    idSourceName: "berlin",
    main: "berlin",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/05c3f9d7dea6422b86e30967811bddd7_0.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Art_Bot",
      common: "Art_Dtsch",
      planted: "Pflanzjahr",
      height: "BaumHoehe",
      location: "Kategorie",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Frankfurt",
    short: "Frankfurt",
    long: "Frankfurt am Main",
    idSourceName: "frankfurt",
    main: "frankfurt",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://hub.arcgis.com/datasets/esri-de-content::baumkataster-frankfurt-am-main",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/8c50110f190e43599baf50701aaff13a_0.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: '(x) => String(x.Gattung_Ar).split(", ")[0]',
      common: '(x) => String(x.Gattung_Ar).split(", ")[1]',
      idReference: "Baumnummer",
      planted: "Pflanzjahr",
      crown: "Kronendurc",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Hamburg Hafen",
    short: "Hamburg Hafen",
    long: "Hamburg Hafen",
    idSourceName: "hamburg_hafen",
    main: "hamburg_hafen",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://hub.arcgis.com/datasets/esri-de-content::stra%C3%9Fenbaumkataster-hamburg-hafen",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/35950460a3744fa4b088570b2df55718_0.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "art_latein",
      common: "art_deutsc",
      note: "sorte",
      planted: "pflanzjahr",
      crown: "kronendurc",
      dbh: "stammumfan",
      owner: "zustaendig",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Rostock",
    short: "Rostock",
    long: "Hanse- und Universitätsstadt Rostock",
    idSourceName: "rostock",
    main: "rostock",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.opendata-hro.de/dataset/baeume",
    broken: false,
    download: "https://geo.sv.rostock.de/download/opendata/baeume/baeume.csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "gattung_botanisch",
      common: "gattung_deutsch",
      height: "hoehe",
      crown: "kronendurchmesser",
      dbh: "stammdurchmesser",
      location: "allebaum",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Chemnitz",
    short: "Chemnitz",
    long: "Chemnitz",
    idSourceName: "chemnitz",
    main: "chemnitz",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://portal-chemnitz.opendata.arcgis.com/datasets/baeume?geometry=12.910%2C50.819%2C12.914%2C50.822",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/70330324e2364b209f7511ca20581f83_0.zip?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "BaumNummer",
      scientific: '(x) => String(x.BaumArt).split(", ")[0]',
      common: '(x) => String(x.BaumArt).split(", ")[1]',
      planted: "PflanzDatu",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Ulm",
    short: "Ulm",
    long: "Ulm",
    idSourceName: "ulm",
    main: "ulm",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://www.daten.ulm.de/datenkatalog/metadaten/baumbestand-stadt-ulm-testdatensatz",
    broken: true,
    download: "http://daten.ulm.de/sites/default/files/20180921_Baeume_1.xlsx",
    format: "xlsx",
    filename: "ulm.vrt",
    gdalOptions: "-skipfailures",
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Baumart_botanisch",
      common: "Baumart",
      height: "Baumhöhe_(aktuell)",
      crown: "Kronendurchm_(aktuell)",
      dbh: "Stammdurchm_(aktuell)",
      health: "Vitalitaetsstatus_(aktuell)",
      planted: "Pflanzjahr_geschaetzt",
      updated: "Standortermittlung_am",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Hamburg",
    short: "Hamburg",
    long: "Hamburg",
    idSourceName: "hamburg",
    main: "hamburg",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: true,
    download:
      "http://daten-hamburg.de/umwelt_klima/strassenbaumkataster/Strassenbaumkataster_HH_2019-06-19.zip",
    format: "zip",
    filename: "Strassenbaumkataster_HH_2019-06-19.gml",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "baumid",
      scientific: "art_latein",
      common: "art_deutsch",
      planted: "pflanzjahr",
      dbh: "stammumfang",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Karlsruhe",
    short: "Karlsruhe",
    long: "Karlsruhe",
    idSourceName: "karlsruhe_de",
    main: "karlsruhe_de",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://transparenz.karlsruhe.de/dataset/fachplane-baumkataster/resource/9cd1989f-9720-4621-b171-3c4e56352598",
    broken: false,
    download:
      "https://geoportal.karlsruhe.de/server/rest/services/Fachplaene/Baumkataster/MapServer/1/query?where=ARTDEUT+IS+NOT+NULL&outFields=ARTDEUT%2CARTLAT&returnGeometry=true&f=geojson",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { common: "ARTDEUT", scientific: "ARTLAT" },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Gelsenkirchen",
    short: "Gelsenkirchen",
    long: "Gelsenkirchen",
    idSourceName: "gelsenkirchen_de",
    main: "gelsenkirchen_de",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://opendata.gelsenkirchen.de/dataset/baumkataster-gelsenkirchen",
    broken: false,
    download:
      "https://opendata.gelsenkirchen.de/sites/default/files/baumkataster_ge.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "BAUMART",
      planted: "PFLANZJAHR",
      crown: "KRONENDURCHMESSER",
      height: "HOEHE",
      idReference: "BAUMID",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Troisdorf",
    short: "Troisdorf",
    long: "Stadt Troisdorf",
    idSourceName: "troisdorf_de",
    main: "troisdorf_de",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://www.stadtplan.troisdorf.de/opengeodata/opendata/open_data_baumkataster.html",
    broken: true,
    download:
      "http://www.stadtplan.troisdorf.de/opengeodata/opendata/data/Troisdorf_Baumkataster_180926.zip",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      height: "Baumhoehe",
      scientific: '(x) => x.Baumart.split(", ")[0]',
      common: '(x) => x.Baumart.split(", ")[1]',
      crown: "Kronendurchmesser",
      dbh: "Stammumfang",
    },
  },
  {
    isoAlpha2: 'DE',
    isoAlpha3: 'DEU',
    numericCountryCode: '276',
    country: "Germany",
    city: "Jena",
    short: "Jena",
    long: "Jena",
    idSourceName: "jena_de",
    main: "jena_de",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://opendata.jena.de/dataset/baumkataster",
    broken: false,
    download:
      "https://opendata.jena.de/dataset/acd67e0c-b597-48c7-b251-1b565c49de90/resource/3ff727bb-8db4-4b47-9c53-7084d15f73d6/download/baumkataster.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      height: "baumhoehe",
      idReference: "baumnummer",
      scientific: "ga_lang",
      dbh: "st_umfang",
      health: "vitalitaet",
    },
  },
];
