export default [
  {
    country: "Argentina",
    city: "Buenos Aires",
    short: "Buenos Aires",
    long: "Buenos Aires",
    id: "buenos_aires",
    id_city_name: "buenos_aires",
    primary: "buenos_aires",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.buenosaires.gob.ar/dataset/arbolado-espacios-verdes",
    srs: null,
    brokenDownload: false,
    download:
      "http://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-en-espacios-verdes/arbolado-en-espacios-verdes.csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "id_arbol",
      height: "altura_tot",
      dbh: "diametre",
      common: "nombre_com",
      scientific: "nombre_cie",
      family: "nombre_fam",
    },
  },
  {
    country: "Argentina",
    city: "Buenos Aires",
    short: "Buenos Aires",
    long: "Buenos Aires",
    id: "buenos_aires2",
    id_city_name: "buenos_aires2",
    primary: "buenos_aires",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.buenosaires.gob.ar/dataset/arbolado-publico-lineal",
    srs: null,
    brokenDownload: false,
    download:
      "http://cdn.buenosaires.gob.ar/datosabiertos/datasets/arbolado-publico-lineal/arbolado-publico-lineal-2017-2018.geojson",
    format: "geojson",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "nro_registro",
      scientific: "nombre_cientifico",
      dbh: "diametro_altura_pecho",
      height: "altura_arbol",
    },
  },
  {
    country: "New Zealand",
    city: "Palmerston North",
    short: "Palmerston North",
    long: "Palmerston North",
    id: "palmerston_north",
    id_city_name: "palmerston_north",
    primary: "palmerston_north",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://data-pncc.opendata.arcgis.com/datasets/077787e2299541bc8d2c2dbf8d7dc4e4_18/data",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/077787e2299541bc8d2c2dbf8d7dc4e4_18.zip?outSR=%7B%22latestWkid%22%3A2193%2C%22wkid%22%3A2193%7D",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { scientific: "botanical_", common: "species" },
  },
  {
    country: "Switzerland",
    city: "Basel",
    short: "Basel",
    long: "Basel",
    id: "basel",
    id_city_name: "basel",
    primary: "basel",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.bs.ch/explore/dataset/100052/information/",
    srs: null,
    brokenDownload: false,
    download:
      "https://data.bs.ch/explore/dataset/100052/download/?format=shp&timezone=Australia/Sydney&lang=en",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: '(x) => String(x.art).replace(/ \\(.*/, "")',
      common: '(x) => (String(x.art).match(/\\((.*)\\)/) || ["", ""])[1]',
      planted: "pflanzdatu",
      age: "baumalter",
    },
  },
  {
    country: "Norway",
    city: "Oslo",
    short: "Oslo",
    long: "Oslo",
    id: "oslo",
    id_city_name: "oslo",
    primary: "oslo",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://hub.arcgis.com/datasets/f256d2d837554edab8b53bb6af90bc8d_19?geometry=10.516%2C59.709%2C10.873%2C59.884",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/f256d2d837554edab8b53bb6af90bc8d_19.zip",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "last_edi_1",
      scientific: "BotNavn",
      common: "Artsnavn",
    },
  },
  {
    country: "Luxembourg",
    city: "Luxembourg",
    short: "Luxembourg",
    long: "Grand-Duchy of Luxembourg",
    id: "luxembourg",
    id_city_name: "luxembourg",
    primary: "luxembourg",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/metadata/bf367452-c965-4ae1-b652-bd2c86400be5",
    srs: null,
    brokenDownload: false,
    download:
      "https://download.data.public.lu/resources/inspire-annex-i-theme-protected-sites-remarkable-trees/20200129-134525/ps.protectedsitesnatureconservation-trees.gml",
    format: "gml",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "localId",
      scientific: '(x) => String(x.text).split(" - ")[0]',
      common: '(x) => String(x.text).split(" - ")[1]',
    },
  },
  {
    country: "Chile",
    city: "Chile (OSM)",
    short: "Chile (OSM)",
    long: "Chile (OSM)",
    id: "chile-osm",
    id_city_name: "chile-osm",
    primary: "chile-osm",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download: "https://emscycletours.site44.com/opentrees-data/chile.geojson",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { common: "name" },
  },
  {
    country: "Italy",
    city: "Bologna",
    short: "Bologna",
    long: "Comune di Bologna",
    id: "bologna_it",
    id_city_name: "bologna_it",
    primary: "bologna_it",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://dati.comune.bologna.it/node/207",
    srs: null,
    brokenDownload: false,
    download: "http://dati.comune.bologna.it/download/file/fid/3989",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "decodifi_4",
      circumference: "decodifi_2",
      ref: "NUM_PT",
    },
  },
  {
    country: "Italy",
    city: "Villa_Manin",
    short: "Villa_Manin",
    long: "Villa_Manin",
    id: "villa_manin_it",
    id_city_name: "villa_manin_it",
    primary: "villa_manin_it",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.dati.friuliveneziagiulia.it/dataset/Alberi-di-Villa-Manin/uqpq-dr8x",
    srs: null,
    brokenDownload: false,
    download:
      "https://www.dati.friuliveneziagiulia.it/api/views/uqpq-dr8x/rows.csv?accessType=DOWNLOAD",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      location: "dove",
      scientific: "specie",
      family: "familia",
      updated: "data rilievo",
    },
  },
  {
    city: "Monterrey",
    short: "Monterrey",
    long: "Zona Metropolitana de Monterrey",
    id: "monterrey_mx",
    id_city_name: "monterrey_mx",
    primary: "monterrey_mx",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://datamx.io/dataset/arboles-registrados-en-la-zona-metropolitana-de-monterrey",
    srs: null,
    brokenDownload: false,
    download:
      "http://datamx.io/dataset/9ad2f30b-4be9-4abe-beac-aec73ecc9cba/resource/6f1f1fe9-40c7-4527-8e2e-78b0f0c86a40/download/bumfiltercsv.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "Arbol_id",
      planted:
        '(x) =>\n        x.Fecha_plantado !== "0000-00-00" ? x.Fecha_plantado : null',
      common: "Especie",
      updated: "Fecha_registro",
    },
  },
];
