export default [
  {
    country: "Ireland",
    city: "Fingal",
    short: "Fingal",
    long: "Fingal County",
    id: "fingal",
    id_city_name: "fingal",
    primary: "fingal",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.fingal.ie/datasets/FingalCoCo::trees-fcc-1/explore",
    srs: null,
    brokenDownload: false,
    download: "https://opendata.arcgis.com/api/v3/datasets/1e5f9db62e53443d946c15a1a06fd98b_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1",
    format: "geojson",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "(x) => Math.round(x.TREE_ID)",
      scientific: "Species_Desc",
      common: "Common_Name",
      maturity: "Age_Desc",
      height: "Height",
      spread: "Spread",
      dbh: '(x) => (x.Actual_Trunk || "").replace("cm", "")',
      health: "Condition",
    },
  },
];
