export default [
  {
    country: "Ireland",
    city: "Fingal",
    short: "Fingal",
    long: "Fingal County",
    id: "fingal",
    id_city_name: "fingal",
    primary: "fingal",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.smartdublin.ie/dataset/tableview/ebf9151e-fd30-442e-93cb-fa88c2affc93",
    srs: null,
    download: "http://data.fingal.ie/datasets/csv/Trees.csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "(x) => Math.round(x.TREE_ID)",
      scientific: "Species_Desc",
      common: "Common_Name",
      maturity: "Age_Desc",
      height: "Height",
      spread: "Spread",
      dbh: '(x) => (x.Actual_Trunk || "").replace("cm", "")',
      health: "Condition",
    },
  },
];
