export default [
  {
    country: "Italy",
    city: "Bologna",
    short: "Bologna",
    long: "Comune di Bologna",
    id: "bologna_it",
    id_city_name: "bologna_it",
    primary: "bologna_it",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://dati.comune.bologna.it/node/207",
    srs: null,
    brokenDownload: false,
    download: "http://dati.comune.bologna.it/download/file/fid/3989",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "decodifi_4",
      circumference: "decodifi_2",
      ref: "NUM_PT",
    },
  },
  {
    country: "Italy",
    city: "Villa_Manin",
    short: "Villa_Manin",
    long: "Villa_Manin",
    id: "villa_manin_it",
    id_city_name: "villa_manin_it",
    primary: "villa_manin_it",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.dati.friuliveneziagiulia.it/dataset/Alberi-di-Villa-Manin/uqpq-dr8x",
    srs: null,
    brokenDownload: false,
    download:
      "https://www.dati.friuliveneziagiulia.it/api/views/uqpq-dr8x/rows.csv?accessType=DOWNLOAD",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      location: "dove",
      scientific: "specie",
      family: "familia",
      updated: "data rilievo",
    },
  },
];
