export default [
  {
    country: "Portugal",
    city: "Lisbon",
    short: "Lisbon",
    long: "Lisbon",
    id: "lisbon",
    id_city_name: "lisbon",
    primary: "lisbon",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://geodados.cm-lisboa.pt/datasets/arvoredo?geometry=-9.312%2C38.745%2C-9.148%2C38.768",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/202d0f1a7f234e449761af8af14436d6_0.zip",
    format: "zip",
    filename: "Arvoredo.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { scientific: "ESPECIE_VA", location: "LOCAL" },
  },
];
