const FEET = 3.280084;
const INCHES = 2.54;

function numeric(x) {
    return Number.isFinite(x) ? x : null;
}

function inches(field) {
    return tree => numeric(Number(tree[field]) * 2.54);
}

function feet(field) {
    return tree => numeric(Number(tree[field]) / 3.280084);
}

const country = [
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
  }
]

export default [
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "WI",
    city: "Madison",
    short: "Madison",
    long: "Madison",
    idName: "madison",
    main: "madison",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/b700541a20e446839b18d62426c266a3_0.zip",
    format: "zip",
    filename: "Street_Trees.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { 
      common: "SPECIES", 
      scientific: "SPECIES",
      dbh: (x) => numeric(Number(x.DIAMETER) * INCHES),
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "OR",
    city: "Portland",
    short: "Portland",
    long: "Portland, Oregon",
    idName: "pdx_street",
    main: "pdx_street",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/eb67a0ad684d4bb6afda51dc065d1664_25.zip",
    format: "zip",
    filename: "Street_Trees.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Scientific",
      genus: "Genus",
      family: "Family",
      common: "Common",
      health: "Condition",
      dbh: (x) => Math.round(x.DBH * 2.54 * 10) / 10,
      note: "Notes",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "OR",
    city: "Portland, Oregon",
    short: "Portland, Oregon",
    long: "Portland, Oregon",
    idName: "pdx_park",
    main: "pdx_street",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/83a7e3f6a1d94db09f24849ee90f4be2_220.zip?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D&session=undefined",
    format: "zip",
    filename: "Parks_Tree_Inventory.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: (x) => Math.round(x.DBH * 2.54 * 10) / 10,
      height: (x) => Math.round((x.HEIGHT / 3.280084) * 10) / 10,
      health: "Condition",
      crown: "CrownWidth",
      family: "Family",
      scientific: "Genus_spec",
      common: "Common_nam",
      note: "Species_fa",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CT",
    city: "New Haven",
    short: "New Haven",
    long: "New Haven",
    idName: "new_haven",
    main: "new_haven",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://urban-resources-initiative.carto.com/me",
    broken: false,
    download:
      "https://urban-resources-initiative.carto.com/api/v2/sql?filename=newhavenstreettrees_carto_mapping_05242022&q=select+*+from+public.newhavenstreettrees_carto_mapping_05242022&format=csv&bounds=&api_key=&skipfields=the_geom_webmercator,the_geom",
    format: "csv",
    filename: "new_haven.csv",
    gdalOptions: null,
    license: null,
    email: "colleen.murphy-dunning@yale.edu",
    contact: "Colleen Murphy-Dunning",
    crosswalk: {
      common: "name",
      scientific: "species",
      genus: "genus",
      species: "species2",
      dbh: "dbh",
      planted: "planting",
      address: "address",
      idReference: "cartodb_id"
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NY",
    city: "New York City",
    short: "New York City",
    long: "New York City",
    idName: "nyc",
    main: "nyc",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cityofnewyork.us/browse?q=tree&sortBy=relevance",
    broken: false,
    download:
      // "https://data.cityofnewyork.us/api/views/uvpi-gqnh/rows.csv?accessType=DOWNLOAD",
      "https://data.cityofnewyork.us/api/views/5rq2-4hqu/rows.csv?accessType=DOWNLOAD",
      // "https://data.cityofnewyork.us/api/geospatial/pi5s-9p35?method=export&format=GeoJSON",
      // "https://data.cityofnewyork.us/api/views/k5ta-2trh/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    // format: "geojson",
    filename: "nyc.csv",
    // filename: "2015 Street Tree Census - Tree Data.geojson",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "tree_id",
      dbh: "tree_dbh",
      scientific: "spc_latin",
      common: "spc_common",
      genus: (x) => x.spc_latin.split(" ")[0],
      health: "health",
      idReference: "tree_id",
      address: "address",
      zipcode: "postcode",
      neighborhood: "borough",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NY",
    city: "New York City",
    short: "New York City",
    long: "New York City",
    idName: "nyc_forest",
    main: "nyc",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cityofnewyork.us/browse?q=tree&sortBy=relevance",
    broken: false,
    download:
      "https://data.cityofnewyork.us/api/views/k5ta-2trh/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: "nyc-forest.csv",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "tree_id",
      dbh: "tree_dbh",
      scientific: "spc_latin",
      common: "spc_common",
      genus: (x) => x.spc_latin.split(" ")[0],
      health: "health",
      idReference: "tree_id",
      address: "address",
      zipcode: "postcode",
      neighborhood: "borough",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "RI",
    city: "Providence",
    short: "Providence",
    long: "Providence, Rhode Island",
    idName: "providence",
    main: "providence",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://data.providenceri.gov/api/views/uv9w-h8i4/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Species",
      dbh: (x) => numeric(Number(x["Diameter in Inches"]) * INCHES),
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "DC",
    city: "Washington DC",
    short: "Washington DC",
    long: "Washington DC",
    idName: "washington_dc",
    main: "washington_dc",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/f6c3c04113944f23a7993f2e603abaf2_23.zip",
    format: "zip",
    filename: "Urban_Forestry_Street_Trees.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "SCI_NM",
      genus: "GENUS_NAME",
      common: "CMMN_NM",
      dbh: "DBH",
      health: "CONDITION",
      updated: "LAST_EDITED_DATE",
      planted: "DATE_PLANT",
      family: "FAM_NAME",
      note: "TREE_NOTES"
      // map additional crown fields
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NY",
    city: "Buffalo",
    short: "Buffalo",
    long: "City of Buffalo, NY",
    idName: "buffalo",
    main: "buffalo",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://data.buffalony.gov/api/views/n4ni-uuec/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Botanical Name",
      common: "Common Name",
      dbh: (x) => numeric(Number(x.DBH) * 2.54),
      idReference: "Site ID",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "PA",
    city: "Philadelphia",
    short: "Philadelphia",
    long: "City of Philadelphia",
    idName: "philadelphia",
    main: "philadelphia",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://opendata.arcgis.com/api/v3/datasets/30ef36e9e880468fa74e2d5b18da4cfb_0/downloads/data?format=geojson&spatialRefId=4326",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: "Chris.Park@phila.gov",
    contact: "Chris Park",
    crosswalk: {
      common: (x) => x.TREE_NAME.split(' - ')[1],
      scientific: (x) => x.TREE_NAME.split(' - ')[0],
      dbh: "TREE_DBH",
      planted: "YEAR",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CO",
    city: "Denver",
    short: "Denver",
    long: "Denver",
    idName: "denver",
    main: "denver",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    broken: false,
    download:
      "https://data.colorado.gov/api/views/wz8h-dap6/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "SITE_ID",
      scientific: "SPECIES_BO",
      common: "SPECIES_CO",
      dbh: "DIAMETER",
      location: "LOCATION_NAME",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CO",
    city: "Boulder",
    short: "Boulder",
    long: "City of Boulder, Colorado",
    idName: "boulder",
    main: "boulder",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data-boulder.opendata.arcgis.com/datasets/dbbae8bdb0a44d17934243b88e85ef2b_0",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/dbbae8bdb0a44d17934243b88e85ef2b_0.zip",
    format: "zip",
    filename: "Tree_Inventory.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "LATINNAME",
      common: "COMMONNAME",
      variety: "CULTIVAR",
      dbh: (x) => "DBHINT" * 2.54,
      location: "LOCTYPE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "MA",
    city: "Cambridge",
    short: "Cambridge",
    long: "Cambridge",
    idName: "cambridge",
    main: "cambridge",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cambridgema.gov/Public-Works/Street-Trees/ni4i-5bnn",
    broken: true,
    download:
      "https://data.cambridgema.gov/api/views/q83f-7quz/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "CommonName",
      scientific: "Scientific",
      idReference: "TreeID",
      dbh: "diameter",
      updated: "last_edite",
      planted: "PlantDate",
      // health: (x) => String(x.TreeCondit).replace(/ \\(.*/, ""),
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Berkeley",
    short: "Berkeley",
    long: "Berkeley",
    idName: "berkeley",
    main: "berkeley",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cityofberkeley.info/Natural-Resources/City-Trees/9t35-jmin",
    broken: false,
    download:
      "https://data.cityofberkeley.info/api/views/x39z-ushg/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: 'trees@cityofberkeley.info',
    phone: 5109816660,
    contact: "City of Berkeley Department of Parks, Recreation & Waterfront",
    crosswalk: {
      common: "common_nam",
      idReference: "siteid",
      scientific: "scientific_name",
      species: "species",
      height: "height_ft",
      spread: "spread_ft",
      dbh: "dbh_in",
      location: "location",
      note: "note",
      health: "condition",
      address: (x) => `${x.strt_num} ${x.strt_name}`,
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "PA",
    city: "Pittsburgh",
    short: "Pittsburgh",
    long: "Pittsburgh",
    idName: "pittsburgh",
    main: "pittsburgh",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.wprdc.org/dataset/city-trees",
    broken: false,
    download:
      "https://data.wprdc.org/dataset/9ce31f01-1dfa-4a14-9969-a5c5507a4b40/resource/d876927a-d3da-44d1-82e1-24310cdb7baf/download/trees_img.geojson",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "common_name",
      idReference: "id",
      scientific: "scientific_name",
      height: "height",
      health: "condition",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "OH",
    city: "Colombus",
    short: "Colombus",
    long: "Colombus",
    idName: "colombus",
    main: "colombus",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://opendata.columbus.gov/datasets/public-owned-trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/674e4a358e8042f69a734f229a93823c_1.zip?outSR=%7B%22wkt%22%3A%22PROJCS%5B%5C%22Ohio%203402%2C%20Southern%20Zone%20(1983%2C%20US%20Survey%20feet)%5C%22%2CGEOGCS%5B%5C%22NAD%2083%20(Continental%20US)%5C%22%2CDATUM%5B%5C%22NAD%2083%20(Continental%20US)%5C%22%2CSPHEROID%5B%5C%22GRS%2080%5C%22%2C6378137.0%2C298.257222101%5D%5D%2CPRIMEM%5B%5C%22Greenwich%5C%22%2C0.0%5D%2CUNIT%5B%5C%22Degree%5C%22%2C0.0174532925199433%5D%5D%2CPROJECTION%5B%5C%22Lambert_Conformal_Conic%5C%22%5D%2CPARAMETER%5B%5C%22False_Easting%5C%22%2C1968500.0%5D%2CPARAMETER%5B%5C%22Central_Meridian%5C%22%2C-82.5%5D%2CPARAMETER%5B%5C%22Standard_Parallel_1%5C%22%2C38.7333333333%5D%2CPARAMETER%5B%5C%22Standard_Parallel_2%5C%22%2C40.0333333333%5D%2CPARAMETER%5B%5C%22Latitude_Of_Origin%5C%22%2C38.0%5D%2CUNIT%5B%5C%22U.S.%20Foot%5C%22%2C0.3048006096012%5D%5D%22%7D",
    format: "zip",
    filename: "Public_Owned_Trees.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "OBJECTID",
      dbh: "DIAM_BREAS",
      updated: "INSPECTION",
      health: "CONDITION1",
      age: "LIFE_STAGE",
      common: "SP_CODE",
      scientific: "SP_NAME",
      note: "STR_NAME",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "TX",
    city: "Austin",
    short: "Austin",
    long: "Austin",
    idName: "austin",
    main: "austin",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://catalog.data.gov/dataset/downtown-tree-inventory-2013",
    broken: false,
    download:
      "https://data.austintexas.gov/api/views/7aq7-a66u/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "SPECIES",
      common: "COM_NAME",
      dbh: "DBH",
      height: 'HEIGHT',
      health: "CONDITION",
      location: "LAND_TYPE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NY",
    city: "Ithica",
    short: "Cornell University",
    long: "Cornell University",
    idName: "cornell",
    main: "cornell",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://cugir.library.cornell.edu/catalog/cugir-008025",
    broken: false,
    download: "https://cugir-data.s3.amazonaws.com/00/80/25/cugir-008025.zip",
    format: "zip",
    filename: "cugir-008025/CornellTree2009.shp",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Botanic",
      common: "Common",
      dbh: 'DBH',
      note: "Comment",
      updated: "SurveyDate",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NC",
    city: "Cary",
    short: "Cary",
    long: "Cary",
    idName: "cary",
    main: "cary",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.townofcary.org/pages/homepage/",
    broken: true,
    broken_reason: "Broken link, old data source does not have species and common fields. Requires outreach.",
    download:
      "https://data.townofcary.org/api/v2/catalog/datasets/cary-trees/exports/csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "editdate",
      common: "name",
      note: "description",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NY",
    city: "Rochester",
    short: "Rochester",
    long: "Rochester",
    idName: "rochester",
    main: "rochester",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/RochesterNY::trees-open-data",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/4c209944e2984b4a908a14b0cbe48075_0.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      note: "TREE_NAME",
      health: "COND",
      dbh: 'DBH',
      idReference: "TREE_NUMBE",
      note: "NOTES",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "WA",
    city: "Seattle",
    short: "Seattle",
    long: "Seattle",
    idName: "seattle",
    main: "seattle",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/SeattleCityGIS::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/0b8c124ace214943ab0379623937eccb_6.zip",
    format: "zip",
    filename: null,
    gdalOptions: null,
    license: null,
    email: "treesforseattle@seattle.gov",
    phone: 2066848733,
    contact: "Trees for Seattle",
    crosswalk: {
      idReference: "UNITID",
      health: "CONDITION",
      owner: "OWNERSHIP",
      updated: "LAST_VERIF",
      planted: "PLANTED_DA",
      common: "COMMON_NA",
      scientific: "SCIENTIFIC",
      address: "UNITDESC",
      common: "BOTANICAL_",
      height: 'TREEHEIGHT',
      dbh: 'DIAM',
      condition: (x) => ["Very poor", "Poor", "Fair", "Good", "Excellent"][x.CONDITION - 1],
      owner: "OWNERSHIP",
      updated:"LAST_VERIF",

    },
},
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Cupertino",
    short: "Cupertino",
    long: "Cupertino",
    idName: "cupertino",
    main: "cupertino",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/Cupertino::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/caa50a924b7d4b5ba8e8a4cbfd0d7f13_29.csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "AssetID",
      updated: "UpdateDate",
      scientific: "Species",
      common: "SpeciesCommonName",
      dbh: 'DiameterBreastHeight',
      height: 'Height',
      location: "LocationType",
      health: "Condition",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Oxnard",
    short: "Oxnard",
    long: "City of Oxnard",
    idName: "oxnard",
    main: "oxnard",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/a5aa2d1dfd344ef79d61507d33cdbc02_1",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/a5aa2d1dfd344ef79d61507d33cdbc02_1.csv",
    format: "csv",
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "BOTANICALN",
      common: "COMMONNAME",
      dbh: 'DBH',
      height: 'HEIGHT',
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NC",
    city: "Wake Forest",
    short: "Wake Forest",
    long: "Town of Wake Forest",
    idName: "wake_forest",
    main: "wake_forest",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/wakeforestnc::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/ba930858554a43cca1be2f06a44d2449_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "LatinName",
      common: "CommonName",
      genus: "Genus",
      health: "conditionO",
      scientific: "SPECIES_LA",
      common: "SPECIES_CO",
      address: "Address",
      dbh: 'DBHRange',
      height: 'TreeHeight',
      location: "Locationon",
      notes: "Maintenac",
      idReference:  "TreeID",
      count: "TreeNumber",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CO",
    city: "Aurora",
    short: "Aurora",
    long: "Aurora",
    idName: "aurora",
    main: "aurora",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AuroraCo::trees-city",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/1dbb32bf07ca421db4f01dac6beb812d_85.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "TREE_ID_NO",
      common: "SPECIES",
      scientific: "SPECIES",
      dbh: 'DIAMETER',
      health: "CONDITION",
      updated: "ACTIVITY_DATE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Bakersfield",
    short: "Bakersfield",
    long: "Bakersfield",
    idName: "bakersfield",
    main: "bakersfield",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/cob::city-trees?geometry=-129.468%2C33.767%2C-108.539%2C36.903",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/b7a17f7ecb564be4b26ced85016ed1da_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "DATE_",
      scientific: "BOTANICAL_",
      common: "COMMON_N",
      dbh: (x) => tree[x],
      height: (x) => tree[x],
      crown: (x) => tree[x],
      health: "RATING",
      note: "COMMENT",
      idReference: "TREE_ID",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NV",
    city: "Las Vegas",
    short: "Las Vegas",
    long: "Las Vegas",
    idName: "las_vegas",
    main: "las_vegas",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/lasvegas::trees",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/23364bb40f2640ff841ba4a8680b6421_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      location: "LOC_TYPE",
      scientific: "BOTANICAL",
      common: "COMMON",
      dbh: "DBH",
      spread: "WIDTH",
      height: "HEIGHT",
      health: "COND",
      note: "NOTES",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Three Rivers",
    short: "Three Rivers",
    long: "Three Rivers Park District",
    idName: "three_rivers",
    main: "three_rivers",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/trpd::managed-trees-open-data?geometry=-96.405%2C44.562%2C-90.563%2C45.243",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/ffbb9401412141a79c7164ade8d2ee2d_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "CommonName",
      scientific: "ScientificName",
      planted: "YearPlanted",
      idReference: "CartedID",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "TX",
    city: "Richardson",
    short: "Richardson",
    long: "Richardson",
    id: "richardson",
    idName: "richardson",
    main: "richardson",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/richardson::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/cd10a9e85354488dbdb697ce97ccb064_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "FACILITYID",
      common: "NAME",
      genus: "GENUS",
      species: "SPECIES",
      scientific: "SPECIES",
      age: "TREEAGE",
      dbh: "DIAMETER",
      height: "HEIGHT",
      owner: "OWNEDBY",
      structure: "TRUNKSTRCT",
      note: "COMMENTS",
      updated: "last_edited_date",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "PA",
    city: "Allentown",
    short: "Allentown",
    long: "City of Allentown",
    idName: "allentown",
    main: "allentown",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AllentownPA::city-trees",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/4383052db35e4f93bbd83e5bde468a00_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "TR_COMMON",
      scientific: "TR_GENUS",
      // dbh: 'DBH',,
      health: "CONDITION",
      updated: "INPUT_DATE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "SD",
    city: "Sioux Falls",
    short: "Sioux Falls",
    long: "Sioux Falls",
    idName: "sioux_falls",
    main: "sioux_falls",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/cityofsfgis::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/c880d62ae5fb4652b1f8e6cbca244107_10.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "AssetID",
      location: "Location",
      common: "FullName",
      scientific: "Species",
      family: "Family",
      spread: "Spread",
      height: "Height",
      dbh: "DBH",
      health: "Condition",
      note: "SpecialComments",
      updated: "last_edited_date",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "MA",
    city: "Amherst",
    short: "Amherst",
    long: "Amherst",
    idName: "amherst",
    main: "amherst",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AmherstMA::street-trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/b4a74ab24f114f22b438a19e589f6f76_0.zip",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "TreeID",
      updated: "LastEdit",
      common: "Species",
      scientific: "Species",
      note: "Notes",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CO",
    city: "Colorado Springs",
    short: "Colorado Springs",
    long: "Colorado Springs",
    idName: "colorado_springs",
    main: "colorado_springs",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/coloradosprings::trees/data?geometry=-106.259%2C38.699%2C-103.338%2C39.073",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/91758518026d4b1089f2180602399d73_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "Common_Name",
      scientific: "Scientific_Name",
      dbh: "DBH",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "OH",
    city: "Marysville",
    short: "Marysville",
    long: "City of Marysville",
    idName: "marysville",
    main: "marysville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/Marysville::individual-trees-sites",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/44b6c7a1307d48ff99d2034b5695c149_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "treeid",
      common: "common",
      genus: "genus",
      species: "sp_epith",
      scientific: "sp_epith",
      variety: "variety",
      location: "type",
      dbh: 'DBH',
      height: 'Height',
      health: "trcond",
      updated: "last_edited_date",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "MO",
    city: "Springfield",
    short: "Springfield",
    long: "City of Springfield",
    idName: "springfield",
    main: "springfield",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/COSMO::tree-inventory",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/7a890a7b54d6438f80bd60e5e34c8e62_34.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      health: "Condition",
      common: "TreeType",
      scientific: "SciName",
      height: "Height",
      dbh: 'DBH',
      spread: "Spread",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Anaheim",
    short: "Anaheim",
    long: "Anaheim",
    idName: "anaheim",
    main: "anaheim",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data-anaheim.opendata.arcgis.com/datasets/city-trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/0f96c6cf73904424bc9ce14197990201_41.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "COMMONNAME",
      scientific: "BOTANICALNAME",
      dbh: "DBH",
      height: "HEIGHT",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NC",
    city: "Charlottesville",
    short: "Charlottesville",
    long: "Charlottesville",
    idName: "charlottesville",
    main: "charlottesville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/charlottesville::tree-inventory-point",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/e7c856379492408e9543a25d684b8311_79.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      planted: "Install_Date",
      common: "Common_Name",
      scientific: "Scientific_Name",
      owner: "Agency",
      genus: "Genus",
      species: "Species",
      updated: "last_edited_date",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "PA",
    city: "West Chester",
    short: "West Chester",
    long: "West Chester Borough",
    idName: "west_chester",
    main: "west_chester",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/WCUPAGIS::borotrees-1?geometry=-87.273%2C38.460%2C-63.905%2C41.408",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/7fdf2b5d2b674e99b33e8d77d052e30c_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: 'DBH',
      idReference: "ID_1",
      genus: "Genus",
      species: "Species_1",
      common: "CommonName",
      scientific: "Species_1",
      health: "Condition_1",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CO",
    city: "Durango",
    short: "Durango",
    long: "Durango",
    idName: "durango",
    main: "durango",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CityOfDurango::city-trees",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/3e3e00d6224b43ee9acc514244fffdb9_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      planted: "DATEID",
      idReference: "ID",
      common: "COMMON",
      genus: "GENUS",
      species: "SPECIES",
      scientific: "SPECIES",
      variety: "CULTIVAR",
      dbh: 'DBH',
      health: "CONDITION",
      updated: "LASTMODDATE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "ME",
    city: "Washington",
    short: "Washington",
    long: "Washington County",
    idName: "washington",
    main: "washington",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/WCMN::tree-inventory",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/ae14fc063c1e44a995e750805b1c864b_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "Tree_Type",
      health: "Health",
      note: "Comments",
      idReference: "OBJECTID",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "OH",
    city: "Westerville",
    short: "Westerville",
    long: "Westerville",
    idName: "westerville",
    main: "westerville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/Westerville::comm-parks-rec-trees/data?geometry=-83.315%2C40.085%2C-82.585%2C40.177",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/137785bc78da47b4a2159f9c76218d55_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: 'DBH',
      common: "COMMON_NAME",
      location: "TREE_TYPE",
      health: "CONDITION",
      scientific: "SCIENTIFIC",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "FL",
    city: "St Augustine",
    short: "St Augustine",
    long: "St Augustine",
    idName: "st_augustine",
    main: "st_augustine",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/STAUG::trees?geometry=-93.005%2C28.223%2C-69.637%2C31.556",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/8372c7d0f5a24764bd10f62f0b2f1b65_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "INSPECT_DT",
      note: "NOTES",
      scientific: "SPP",
      dbh: "DBH",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "FL",
    city: "Weston",
    short: "Weston",
    long: "Weston",
    idName: "weston",
    main: "weston",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/westonfl::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/c95f89a4db39414a89f5c29bcb6fb48d_6.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "NAME",
      genus: "GENUS",
      species: "SPECIES",
      age: "TREEAGE",
      dbh: 'DBH',
      height: 'Height',
      health: "CONDITION",
      owner: "OWNEDBY",
      updated: "LASTUPDATE",
      scientific: "BOTNAME",
      family: "FAMILY",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Pacific Grove",
    short: "Pacific Grove",
    long: "Pacific Grove",
    idName: "pacific_grove",
    main: "pacific_grove",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CityPacificGrove::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/87bcc6e824214422be859b3251350829_3.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "Type",
      scientific: "BOTANICAL",
      variety: "CULTIVAR",
      dbh: 'DBH',
      condition: (x) => String(x.CONDITION).split(" - ")[0],
      note: "NOTES",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "MT",
    city: "Bozeman",
    short: "Bozeman",
    long: "City of Bozeman",
    idName: "bozeman",
    main: "bozeman",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/bozeman::trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/ba0dea7927184014a8b84e64af5c7684_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      genus: "Genus",
      species: "Species",
      variety: "Cultivar",
      dbh: 'DBH',
      health: "Condition",
      updated: "last_edited_date",
      common: "Common_Name",
      idReference: "FacilityID",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "IL",
    city: "Champaign",
    short: "Champaign",
    long: "Champaign",
    idName: "champaign",
    main: "champaign",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/cityofchampaign::city-owned-trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/979bbeefffea408e8f1cb7a397196c64_22.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "ID",
      scientific: "SPP",
      common: "COMMON",
      dbh: 'DBH',
      health: "COND",
      updated: "INSPECT_DT",
      note: "NOTES",
      family: "FAMILY",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Placentia",
    short: "Placentia",
    long: "Placentia",
    idName: "placentia",
    main: "placentia",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/placentia::city-trees",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/8efcbe9c80ed42a29e6ad5483bd01c32_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "INVENTORYI",
      scientific: "BOTANICALN",
      common: "COMMONNAME",
      dbh: "DBH",
      height: "HEIGHT",
      updated: "EditDate",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "FL",
    city: "Sarasota",
    short: "Sarasota",
    long: "Sarasota",
    idName: "sarasota",
    main: "sarasota",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/sarasota::tree-inventory",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/4deeb30f44bc4b60847cf43aed1a4670_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Species",
      dbh: 'DBH',
      height: 'Height',
      health: "Condition",
      owner: "Ownership",
      note: "Notes",
      updated: "last_edited_date",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "MI",
    city: "Ann Arbor",
    short: "Nichols Arboretum",
    long: "Nichols Arboretum",
    idName: "nichols_arboretum",
    main: "nichols_arboretum",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/umich::nichols-arboretum-inventory-survey",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/febee55e7dac43298952af77c8f8d809_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "COMMON",
      scientific: "BOTANICAL",
      variety: "CULTIVAR",
      dbh: 'DBH',
      health: "COND",
      note: "NOTES",
      updated: "DATE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "TX",
    city: "Denton",
    short: "UNT",
    long: "University of North Texas",
    idName: "unt",
    main: "unt",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/untgis::tree",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/ee33bf4535cd47bbb1c5661d2333d834_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { note: "NOTES", common: "NAME_COMN", idReference: "UNT_ID" },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Escondido",
    short: "Escondido",
    long: "City of Escondido",
    idName: "escondido",
    main: "escondido",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CityofEscondido::tree-inventory?geometry=-122.895%2C32.313%2C-111.211%2C33.923",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/ac9caf3c7a9847b78100cc8860ddf51a_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "TREEID",
      scientific: "BOTANICAL",
      common: "COMMON",
      dbh: "DBH_RANGE",
      height: 'Height',
      health: "CONDITION",
      updated: "LAST_EDITED_DATE",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "TX",
    city: "Wylie",
    short: "Wylie",
    long: "City of Wylie",
    idName: "wylie",
    main: "wylie",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/WylieTX::treesurvey",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/82060fffb84045fdafbe2a56c989b353_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "TK_ID",
      common: "COMMON",
      dbh: 'DBH',
      health: "CONDITION",
      updated: "INSPECT_DT",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "ME",
    city: "Auburn",
    short: "Auburn",
    long: "Auburn",
    idName: "auburn",
    main: "auburn",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AuburnME::treeinventory?geometry=-81.930%2C42.701%2C-58.562%2C45.462",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/91bffc476216422481b511a48796a327_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: "ID",
      common: "COMMON",
      scientific: "BOTANICAL",
      dbh: "DBH",
      health: "COND",
      note: "NOTES",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "NY",
    city: "Hudson River Park",
    short: "Hudson River Park",
    long: "Hudson River Park Trust",
    idName: "hudson_river_park",
    main: "hudson_river_park",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/SustainableMSU::tree",
    broken: true,
    download:
      "https://opendata.arcgis.com/datasets/51b5e5da030f4331af48cb052f2d2d5e_1.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Species_Latin_Name",
      common: "Species_Common_Name",
      height: 'Height',
      dbh: 'DBH',
      structure: "Structural_Value",
      idReference: "HRPT_Numbering_1",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "FL",
    city: "Cape Coral",
    short: "Cape Coral",
    long: "Cape Coral",
    idName: "cape_coral",
    main: "cape_coral",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CapeGIS::tree-inventory",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/e988fe06668e44ea996a53c4365531b9_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "SPECIES",
      dbh: "DBH",
      crown: "CANOPY",
      location: "SITE",
      health: "CONDITION",
      updated: "last_edited_date",
      height: "HEIGHT",
      note: "COMMENTS",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "IL",
    city: "Naperville",
    short: "Naperville",
    long: "Naperville",
    idName: "naperville",
    main: "naperville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/naperville::right-of-way-tree-inventory",
    broken: false,
    download:
      "https://www.arcgis.com/sharing/rest/content/items/a6865fd074b54a369ad79c87680af8a9/data",
    format: "csv",
    filename: "naperville.csv",
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "CULTIVAR",
      scientific: "FAMILY",
      family: "FAMILY",
      variety: "CULTIVAR",
      genus: "GENUS",
      idReference: "FACILITYID",
      health: "CONDITION_CLASS",
      updated: "DATE_CHANGED",
      planted: "DatePlanted",
      who: "PLANTED_BY",
      dbh: 'DIAMETER',
      note: "COMMENT",
      neighborhood: "DISTRICT",
      address: (x) => `${x.ADDRESS_NUMBER} ${x.ADDRESS_STREET}`,
    },
   },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Alameda",
    short: "Alameda",
    long: "Alameda",
    idName: "alameda",
    main: "alameda",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.arboraccess.com/Custom/Alameda/Public/TreeInventoryMap.aspx?Width=1000&Height=800",
    broken: false,
    download: "https://waterthetrees.com/api/csv?city=Alameda",
    format: 'csv',
    filename: 'alameda.csv',
    gdalOptions: null,
    license: null,
    email: "pw@alamedaca.gov",
    contact: "Erin Smith",
    crosswalk: {
      common: 'common',
      idReference: "idReference",
      health: "health",
      height: "height",
      address: "address",
      planted: "datePlanted",
      dbh: "dbh",
      family: 'scientific'.split(' ')[0],
      species: 'scientific',
      genus: 'genus',
      owner: "owner",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Oakland",
    short: "Oakland",
    long: "Oakland",
    idName: "oakland",
    main: "oakland",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.treesforoakland.org",
    broken: false,
    download: "https://waterthetrees.com/api/csv?city=Oakland",
    format: 'csv',
    filename: 'oakland.csv',
    gdalOptions: null,
    license: null,
    email: "sctreeplanting@gmail.com",
    contact: "Trees for Oakland",
    phone: "510-969-0185",
    crosswalk: {
      common: 'common',
      idReference: "idReference",
      health: "health",
      address: "address",
      planted: "datePlanted",
      dbh: "dbh",
      height: "height",
      family: (x) => x.scientific.split(' ')[0],
      genus: 'genus',
      species: 'scientific',
      scientific: 'scientific',
      owner: "owner",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Pasadena",
    short: "Pasadena",
    long: "Pasadena",
    idName: "pasadena",
    main: "pasadena",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cityofpasadena.net/",
    broken: false,
    download: "https://opendata.arcgis.com/api/v3/datasets/593b88391b614123890f54a1db8fbf55_2/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: "citygis@cityofpasadena.net",
    contact: "City of Pasadena Open Data Site",
    crosswalk: {
      common: "Common_Name",
      genus: "Genus",
      species: "Species",
      dbh: "Trunk_Diameter",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "San Francisco",
    short: "San Francisco",
    long: "San Francisco",
    idName: "san_francisco",
    main: "san_francisco",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.sfgov.org/City-Infrastructure/Street-Tree-List/tkzw-k3nq",
    broken: false,
    download:
      "https://data.sfgov.org/api/views/tkzw-k3nq/rows.csv?accessType=DOWNLOAD",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      idReference: 'TreeID',
      health: 'CONDITION_CLASS',
      updated: 'DATE_CHANGED',
      address: 'qAddress',
      planted: 'PlantDate',
      dbh: 'DBH',
      family: (x) => x.qSpecies.split(' :: ')[0],
      variety: 'qSpecies',
      species: (x) => x.qSpecies.split(' :: ')[0],
      genus: (x) => x.qSpecies.split(' :: ')[0].split(' ')[0],
      common: (x) => x.qSpecies.split(' :: ')[1],
      scientific: (x) => x.qSpecies.split(' :: ')[0],
      owner: 'qLegalStatus',
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "San Jose",
    short: "San Jose",
    long: "San Jose Medians and Backups",
    idName: "san_jose1",
    main: "san_jose1",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/csjdotgis::trees-medians-and-backups",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/0b0ad30145394b1588ff09ef1a7c9225_1.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "NAMESCIENTIFIC",
      age: "TREEAGE",
      dbh: 'DBH',
      height: 'Height',
      crown: 'CROWN',
      health: (x) => String(x.CONDITION).split(" ")[0],
      note: "NOTES",
      updated: "EditDate",
      owner: "OWNEDBY",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "San Jose",
    short: "San Jose",
    long: "San Jose Special Districts",
    idName: "san_jose2",
    main: "san_jose1",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/csjdotgis::trees-special-districts",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/0b0ad30145394b1588ff09ef1a7c9225_0.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "NAMESCIENTIFIC",
      age: "TREEAGE",
      dbh: 'DBH',
      height: 'Height',
      crown: 'CROWN',
      health: (x) => String(x.CONDITION).split(" ")[0],
      note: "NOTES",
      updated: "EditDate",
      owner: "OWNEDBY",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "San Jose",
    short: "San Jose",
    long: "San Jose General Fund",
    idName: "san_jose3",
    main: "san_jose1",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/csjdotgis::trees-general-fund-street",
    broken: false,
    download:
      "https://opendata.arcgis.com/datasets/0b0ad30145394b1588ff09ef1a7c9225_2.csv",
    format: null,
    filename: null,
    gdalOptions: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "NAMESCIENTIFIC",
      age: "TREEAGE",
      dbh: 'DBH',
      height: 'Height',
      crown: 'CROWN',
      health: (x) => String(x.CONDITION).split(" ")[0],
      note: "NOTES",
      updated: "EditDate",
      owner: "OWNEDBY",
    },
  },
  {
    isoAlpha2: 'US',
    isoAlpha3: 'USA',
    numericCountryCode: '840',
    country: "United States of America",
    state: "CA",
    city: "Santa Monica",
    short: "Santa Monica",
    long: "Santa Monica",
    idName: "santa_monica",
    main: "santa_monica",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.smgov.net/",
    broken: false,
    download: "https://opendata.arcgis.com/api/v3/datasets/64f5db2cbb224f6d87387999a300b962_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1",
    format: "geojson",
    filename: null,
    gdalOptions: null,
    license: null,
    email: "data@smgov.net",
    contact: "City of Santa Monica Open Data",
    crosswalk: {
      common: "commonname",
      species: "botanicalname",
      dbh: "actualdbh",
      height: "height",
      note: "recommended",
    },
  },
];
