export default [
  {
    country: "United States",
    state: "WI",
    city: "Madison",
    short: "Madison",
    long: "Madison",
    id: "madison",
    id_city_name: "madison",
    primary: "madison",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/b700541a20e446839b18d62426c266a3_0.zip",
    format: "zip",
    filename: "Street_Trees.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { common: "SPECIES", dbh: (x) => Number(x.DIAMETER) * INCHES },
  },
  {
    country: "United States",
    state: "OR",
    city: "Portland",
    short: "Portland",
    long: "Portland, Oregon",
    id: "pdx-street",
    id_city_name: "pdx-street",
    primary: "pdx-street",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/eb67a0ad684d4bb6afda51dc065d1664_25.zip",
    format: "zip",
    filename: "Street_Trees.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Scientific",
      genus: "Genus",
      family: "Family",
      common: "Common",
      health: "Condition",
      dbh: (x) => Math.round(x.DBH * 2.54 * 10) / 10,
      note: "Notes",
    },
  },
  {
    country: "United States",
    state: "OR",
    city: "Portland, Oregon",
    short: "Portland, Oregon",
    long: "Portland, Oregon",
    id: "pdx-park",
    id_city_name: "pdx-park",
    primary: "pdx-street",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/83a7e3f6a1d94db09f24849ee90f4be2_220.zip?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D&session=undefined",
    format: "zip",
    filename: "Parks_Tree_Inventory.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: (x) => Math.round(x.DBH * 2.54 * 10) / 10,
      height: (x) => Math.round((x.HEIGHT / 3.280084) * 10) / 10,
      health: "Condition",
      crown: "CrownWidth",
      family: "Family",
      scientific: "Genus_spec",
      common: "Common_nam",
      description: "Species_fa",
    },
  },
  {
    country: "United States",
    state: "NY",
    city: "New York",
    short: "New York",
    long: "New York City",
    id: "nyc",
    id_city_name: "nyc",
    primary: "nyc",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://data.cityofnewyork.us/api/views/uvpi-gqnh/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: "nyc.csv",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "tree_id",
      dbh: (x) => x.tree_dbh * 2.54,
      scientific: "spc_latin",
      common: "spc_common",
      health: "health",
    },
  },
  {
    country: "United States",
    state: "RI",
    city: "Providence",
    short: "Providence",
    long: "Providence, Rhode Island",
    id: "providence",
    id_city_name: "providence",
    primary: "providence",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://data.providenceri.gov/api/views/uv9w-h8i4/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Species",
      dbh: (x) => Number(x["Diameter in Inches"]) * INCHES,
    },
  },
  {
    country: "United States",
    state: "DC",
    city: "Washington DC",
    short: "Washington DC",
    long: "Washington DC",
    id: "washington-dc",
    id_city_name: "washington-dc",
    primary: "washington-dc",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/f6c3c04113944f23a7993f2e603abaf2_23.zip",
    format: "zip",
    filename: "Urban_Forestry_Street_Trees.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: (x) => x.DBH * 2.54,
      common: "COMMON.NAME",
      scientific: "SCI_NM",
      planted: "DATE_PLANT",
      family: "FAM_NAME",
      note: "TREE_NOTES",
      health: "CONDITION",
    },
  },
  {
    country: "United States",
    state: "NY",
    city: "Buffalo",
    short: "Buffalo",
    long: "City of Buffalo, NY",
    id: "buffalo",
    id_city_name: "buffalo",
    primary: "buffalo",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://data.buffalony.gov/api/views/n4ni-uuec/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Botanical Name",
      common: "Common Name",
      dbh: (x) => Number(x.DBH) * 2.54,
      id: "Site ID",
    },
  },
  {
    country: "United States",
    state: "PA",
    city: "Philadelphia",
    short: "Philadelphia",
    long: "City of Philadelphia",
    id: "philadelphia",
    id_city_name: "philadelphia",
    primary: "philadelphia",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: true,
    download:
      "http://data.phl.opendata.arcgis.com/datasets/957f032f9c874327a1ad800abd887d17_0.csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {},
  },
  {
    country: "United States",
    state: "CO",
    city: "Denver",
    short: "Denver",
    long: "Denver",
    id: "denver",
    id_city_name: "denver",
    primary: "denver",
    center: null,
    latitude: null,
    longitude: null,
    info: null,
    srs: null,
    brokenDownload: false,
    download:
      "https://data.colorado.gov/api/views/wz8h-dap6/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "SITE_ID",
      scientific: "SPECIES_BO",
      common: "SPECIES_CO",
      dbh: "DIAMETER",
      location: "LOCATION_NAME",
    },
  },
  {
    country: "United States",
    state: "CO",
    city: "Boulder",
    short: "Boulder",
    long: "City of Boulder, Colorado",
    id: "boulder",
    id_city_name: "boulder",
    primary: "boulder",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data-boulder.opendata.arcgis.com/datasets/dbbae8bdb0a44d17934243b88e85ef2b_0",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/dbbae8bdb0a44d17934243b88e85ef2b_0.zip",
    format: "zip",
    filename: "Tree_Inventory.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "LATINNAME",
      common: "COMMONNAME",
      variety: "CULTIVAR",
      dbh: (x) => "DBHINT" * 2.54,
      location: "LOCTYPE",
    },
  },
  {
    country: "United States",
    state: "MA",
    city: "Cambridge",
    short: "Cambridge",
    long: "Cambridge",
    id: "cambridge",
    id_city_name: "cambridge",
    primary: "cambridge",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cambridgema.gov/Public-Works/Street-Trees/ni4i-5bnn",
    srs: null,
    brokenDownload: true,
    download:
      "https://data.cambridgema.gov/api/views/q83f-7quz/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "CommonName",
      scientific: "Scientific",
      ref: "TreeID",
      dbh: "diameter",
      updated: "last_edite",
      planted: "PlantDate",
      // health: (x) => String(x.TreeCondit).replace(/ \\(.*/, ""),
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Berkeley",
    short: "Berkeley",
    long: "Berkeley",
    id: "berkeley",
    id_city_name: "berkeley",
    primary: "berkeley",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.cityofberkeley.info/Natural-Resources/City-Trees/9t35-jmin",
    srs: null,
    brokenDownload: false,
    download:
      "https://data.cityofberkeley.info/api/views/x39z-ushg/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "SPECIES",
      common: "Common_Nam",
      height: (x) => Number(x.HEIGHT_FT) / FEET,
      dbh: (x) => Number(x.DBH_IN) * INCHES,
      health: "CONDITION",
      note: "note",
    },
  },
  {
    country: "United States",
    state: "PA",
    city: "Pittsburgh",
    short: "Pittsburgh",
    long: "Pittsburgh",
    id: "pittsburgh",
    id_city_name: "pittsburgh",
    primary: "pittsburgh",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.wprdc.org/dataset/city-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://data.wprdc.org/dataset/9ce31f01-1dfa-4a14-9969-a5c5507a4b40/resource/d876927a-d3da-44d1-82e1-24310cdb7baf/download/trees_img.geojson",
    format: "geojson",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "common_name",
      ref: "id",
      scientific: "scientific_name",
      height: "height",
      health: "condition",
    },
  },
  {
    country: "United States",
    state: "OH",
    city: "Colombus",
    short: "Colombus",
    long: "Colombus",
    id: "colombus",
    id_city_name: "colombus",
    primary: "colombus",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://opendata.columbus.gov/datasets/public-owned-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/674e4a358e8042f69a734f229a93823c_1.zip?outSR=%7B%22wkt%22%3A%22PROJCS%5B%5C%22Ohio%203402%2C%20Southern%20Zone%20(1983%2C%20US%20Survey%20feet)%5C%22%2CGEOGCS%5B%5C%22NAD%2083%20(Continental%20US)%5C%22%2CDATUM%5B%5C%22NAD%2083%20(Continental%20US)%5C%22%2CSPHEROID%5B%5C%22GRS%2080%5C%22%2C6378137.0%2C298.257222101%5D%5D%2CPRIMEM%5B%5C%22Greenwich%5C%22%2C0.0%5D%2CUNIT%5B%5C%22Degree%5C%22%2C0.0174532925199433%5D%5D%2CPROJECTION%5B%5C%22Lambert_Conformal_Conic%5C%22%5D%2CPARAMETER%5B%5C%22False_Easting%5C%22%2C1968500.0%5D%2CPARAMETER%5B%5C%22Central_Meridian%5C%22%2C-82.5%5D%2CPARAMETER%5B%5C%22Standard_Parallel_1%5C%22%2C38.7333333333%5D%2CPARAMETER%5B%5C%22Standard_Parallel_2%5C%22%2C40.0333333333%5D%2CPARAMETER%5B%5C%22Latitude_Of_Origin%5C%22%2C38.0%5D%2CUNIT%5B%5C%22U.S.%20Foot%5C%22%2C0.3048006096012%5D%5D%22%7D",
    format: "zip",
    filename: "Public_Owned_Trees.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "OBJECTID",
      dbh: (x) => Number("DIAM_BREAS") * INCHES,
      updated: "INSPECTION",
      health: "CONDITION1",
      maturity: "LIFE_STAGE",
      common: "SP_CODE",
      description: "STR_NAME",
    },
  },
  {
    country: "United States",
    state: "TX",
    city: "Austin",
    short: "Austin",
    long: "Austin",
    id: "austin",
    id_city_name: "austin",
    primary: "austin",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://catalog.data.gov/dataset/downtown-tree-inventory-2013",
    srs: null,
    brokenDownload: false,
    download:
      "https://data.austintexas.gov/api/views/7aq7-a66u/rows.csv?accessType=DOWNLOAD",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "SPECIES",
      common: "COM_NAME",
      dbh: (x) => x.DBH * INCHES,
      height: (x) => x.HEIGHT / FEET,
      health: "CONDITION",
      location: "LAND_TYPE",
    },
  },
  {
    country: "United States",
    state: "NY",
    city: "Ithica",
    short: "Cornell University",
    long: "Cornell University",
    id: "cornell",
    id_city_name: "cornell",
    primary: "cornell",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://cugir.library.cornell.edu/catalog/cugir-008025",
    srs: null,
    brokenDownload: false,
    download: "https://cugir-data.s3.amazonaws.com/00/80/25/cugir-008025.zip",
    format: "zip",
    filename: "cugir-008025/CornellTree2009.shp",
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Botanic",
      common: "Common",
      dbh: (x) => x.DBH * INCHES,
      note: "Comment",
      updated: "SurveyDate",
    },
  },
  {
    country: "United States",
    state: "NC",
    city: "Cary",
    short: "Cary",
    long: "Cary",
    id: "cary",
    id_city_name: "cary",
    primary: "cary",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://catalog.data.gov/dataset/cary-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://data.townofcary.org/api/v2/catalog/datasets/cary-trees/exports/csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "editdate",
      common: "name",
      description: "description",
    },
  },
  {
    country: "United States",
    state: "NY",
    city: "Rochester",
    short: "Rochester",
    long: "Rochester",
    id: "rochester",
    id_city_name: "rochester",
    primary: "rochester",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/RochesterNY::trees-open-data",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/4c209944e2984b4a908a14b0cbe48075_0.zip",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      description: "TREE_NAME",
      health: "COND",
      dbh: (x) => String(x.DBH).replace('"', "") * INCHES,
      ref: "TREE_NUMBE",
      note: "NOTES",
    },
  },
  {
    country: "United States",
    state: "WA",
    city: "Seattle",
    short: "Seattle",
    long: "Seattle",
    id: "seattle",
    id_city_name: "seattle",
    primary: "seattle",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/SeattleCityGIS::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/0b8c124ace214943ab0379623937eccb_6.zip",
    format: "zip",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "UNITID",
      health: "CONDITION",
      owner: "OWNERSHIP",
      updated: "LAST_VERIF",
      planted: "PLANTED_DA",
      scientific: "SCIENTIFIC",
      common: "COMMON_NAM",
      height: (x) => x.TREEHEIGHT / FEET,
      dbh: (x) => x.DIAM * INCHES,
      condition: (x) => ["Very poor", "Poor", "Fair", "Good", "Excellent"][x.CONDITIO_3 - 1],
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Cupertino",
    short: "Cupertino",
    long: "Cupertino",
    id: "cupertino",
    id_city_name: "cupertino",
    primary: "cupertino",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/Cupertino::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/caa50a924b7d4b5ba8e8a4cbfd0d7f13_29.csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "AssetID",
      updated: "UpdateDate",
      scientific: "Species",
      common: "SpeciesCommonName",
      dbh: (x) => Number(x.DiameterBreastHeight) * INCHES,
      height: (x) => Number(x.Height) / FEET,
      location: "LocationType",
      health: "Condition",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Oxnard",
    short: "Oxnard",
    long: "City of Oxnard",
    id: "oxnard",
    id_city_name: "oxnard",
    primary: "oxnard",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/a5aa2d1dfd344ef79d61507d33cdbc02_1",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/a5aa2d1dfd344ef79d61507d33cdbc02_1.csv",
    format: "csv",
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "BOTANICALN",
      common: "COMMONNAME",
      dbh: (x) => Number(x.DBH) * INCHES,
      height: (x) => Number(x.HEIGHT) / FEET,
    },
  },
  {
    country: "United States",
    state: "NC",
    city: "Wake Forest",
    short: "Wake Forest",
    long: "Town of Wake Forest",
    id: "wake_forest",
    id_city_name: "wake_forest",
    primary: "wake_forest",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/wakeforestnc::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/ba930858554a43cca1be2f06a44d2449_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "SPECIES_LA",
      common: "SPECIES_CO",
      health: "STATUS",
    },
  },
  {
    country: "United States",
    state: "CO",
    city: "Aurora",
    short: "Aurora",
    long: "Aurora",
    id: "aurora",
    id_city_name: "aurora",
    primary: "aurora",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AuroraCo::trees-city",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/1dbb32bf07ca421db4f01dac6beb812d_85.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "TREE_ID_NO",
      common: "SPECIES",
      dbh: (x) => Number(x.DIAMETER) * INCHES,
      health: "CONDITION",
      updated: "ACTIVITY_DATE",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Bakersfield",
    short: "Bakersfield",
    long: "Bakersfield",
    id: "bakersfield",
    id_city_name: "bakersfield",
    primary: "bakersfield",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/cob::city-trees?geometry=-129.468%2C33.767%2C-108.539%2C36.903",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/b7a17f7ecb564be4b26ced85016ed1da_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "DATE_",
      scientific: "BOTANICAL_",
      common: "COMMON_N",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      crown: (x) => numeric(Number(tree[x]) / 3.280084),
      health: "RATING",
      note: "COMMENT",
      ref: "TREE_ID",
    },
  },
  {
    country: "United States",
    state: "NV",
    city: "Las Vegas",
    short: "Las Vegas",
    long: "Las Vegas",
    id: "las_vegas",
    id_city_name: "las_vegas",
    primary: "las_vegas",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/lasvegas::trees",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/23364bb40f2640ff841ba4a8680b6421_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      location: "LOC_TYPE",
      scientific: "BOTANICAL",
      common: "COMMON",
      dbh: "DBH",
      spread: "WIDTH",
      height: "HEIGHT",
      health: "COND",
      note: "NOTES",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Three Rivers",
    short: "Three Rivers",
    long: "Three Rivers Park District",
    id: "three_rivers",
    id_city_name: "three_rivers",
    primary: "three_rivers",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/trpd::managed-trees-open-data?geometry=-96.405%2C44.562%2C-90.563%2C45.243",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/ffbb9401412141a79c7164ade8d2ee2d_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "CommonName",
      scientific: "ScientificName",
      planted: "YearPlanted",
      ref: "CartedID",
    },
  },
  {
    country: "United States",
    state: "TX",
    city: "Richardson",
    short: "Richardson",
    long: "Richardson",
    id: "richardson",
    id_city_name: "richardson",
    primary: "richardson",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/richardson::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/cd10a9e85354488dbdb697ce97ccb064_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "NAME",
      genus: "GENUS",
      species: "SPECIES",
      age: "TREEAGE",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      owner: "OWNEDBY",
      structure: "TRUNKSTRCT",
      note: "COMMENTS",
      updated: "last_edited_date",
    },
  },
  {
    country: "United States",
    state: "PA",
    city: "Allentown",
    short: "Allentown",
    long: "City of Allentown",
    id: "allentown",
    id_city_name: "allentown",
    primary: "allentown",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AllentownPA::city-trees",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/4383052db35e4f93bbd83e5bde468a00_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "TR_COMMON",
      scientific: "TR_GENUS",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "CONDITION",
      updated: "INPUT_DATE",
    },
  },
  {
    country: "United States",
    state: "SD",
    city: "Sioux Falls",
    short: "Sioux Falls",
    long: "Sioux Falls",
    id: "sioux_falls",
    id_city_name: "sioux_falls",
    primary: "sioux_falls",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/cityofsfgis::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/c880d62ae5fb4652b1f8e6cbca244107_10.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "AssetID",
      location: "Location",
      common: "FullName",
      scientific: "Species",
      family: "Family",
      Spread: "Spread",
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "Condition",
      Note: "SpecialComments",
      updated: "last_edited_date",
    },
  },
  {
    country: "United States",
    state: "MA",
    city: "Amherst",
    short: "Amherst",
    long: "Amherst",
    id: "amherst",
    id_city_name: "amherst",
    primary: "amherst",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AmherstMA::street-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/b4a74ab24f114f22b438a19e589f6f76_0.zip",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "TreeID",
      updated: "LastEdit",
      common: "Species",
      note: "Notes",
    },
  },
  {
    country: "United States",
    state: "CO",
    city: "Colorado Springs",
    short: "Colorado Springs",
    long: "Colorado Springs",
    id: "colorado_springs",
    id_city_name: "colorado_springs",
    primary: "colorado_springs",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/coloradosprings::trees/data?geometry=-106.259%2C38.699%2C-103.338%2C39.073",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/91758518026d4b1089f2180602399d73_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "Common_Name",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
    },
  },
  {
    country: "United States",
    state: "OH",
    city: "Marysville",
    short: "Marysville",
    long: "City of Marysville",
    id: "marysville",
    id_city_name: "marysville",
    primary: "marysville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/Marysville::individual-trees-sites",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/44b6c7a1307d48ff99d2034b5695c149_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "treeid",
      common: "common",
      genus: "genus",
      species: "sp_epith",
      variety: "variety",
      location: "type",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      health: "trcond",
      updated: "last_edited_date",
    },
  },
  {
    country: "United States",
    state: "MO",
    city: "Springfield",
    short: "Springfield",
    long: "City of Springfield",
    id: "springfield",
    id_city_name: "springfield",
    primary: "springfield",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/COSMO::tree-inventory",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/7a890a7b54d6438f80bd60e5e34c8e62_34.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      health: "Condition",
      common: "TreeType",
      scientific: "SciName",
      height: "Height",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      spread: "Spread",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Anaheim",
    short: "Anaheim",
    long: "Anaheim",
    id: "anaheim",
    id_city_name: "anaheim",
    primary: "anaheim",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data-anaheim.opendata.arcgis.com/datasets/city-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/0f96c6cf73904424bc9ce14197990201_41.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "COMMONNAME",
      scientific: "BOTANICALNAME",
      dbh: "DBH",
      height: "HEIGHT",
    },
  },
  {
    country: "United States",
    state: "NC",
    city: "Charlottesville",
    short: "Charlottesville",
    long: "Charlottesville",
    id: "charlottesville",
    id_city_name: "charlottesville",
    primary: "charlottesville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/charlottesville::tree-inventory-point",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/e7c856379492408e9543a25d684b8311_79.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      planted: "Install_Date",
      common: "Common_Name",
      owner: "Agency",
      genus: "Genus",
      species: "Species",
      updated: "last_edited_date",
    },
  },
  {
    country: "United States",
    state: "PA",
    city: "West Chester",
    short: "West Chester",
    long: "West Chester Borough",
    id: "west_chester",
    id_city_name: "west_chester",
    primary: "west_chester",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/WCUPAGIS::borotrees-1?geometry=-87.273%2C38.460%2C-63.905%2C41.408",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/7fdf2b5d2b674e99b33e8d77d052e30c_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      ref: "ID_1",
      genus: "Genus",
      species: "Species_1",
      common: "CommonName",
      health: "Condition_1",
    },
  },
  {
    country: "United States",
    state: "CO",
    city: "Durango",
    short: "Durango",
    long: "Durango",
    id: "durango",
    id_city_name: "durango",
    primary: "durango",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CityOfDurango::city-trees",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/3e3e00d6224b43ee9acc514244fffdb9_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      planted: "DATEID",
      ref: "ID",
      common: "COMMON",
      genus: "GENUS",
      species: "SPECIES",
      variety: "CULTIVAR",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "CONDITION",
      updated: "LASTMODDATE",
    },
  },
  {
    country: "United States",
    state: "ME",
    city: "Washington",
    short: "Washington",
    long: "Washington County",
    id: "washington",
    id_city_name: "washington",
    primary: "washington",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/WCMN::tree-inventory",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/ae14fc063c1e44a995e750805b1c864b_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "Tree_Type",
      health: "Health",
      note: "Comments",
      ref: "OBJECTID",
    },
  },
  {
    country: "United States",
    state: "OH",
    city: "Westerville",
    short: "Westerville",
    long: "Westerville",
    id: "westerville",
    id_city_name: "westerville",
    primary: "westerville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/Westerville::comm-parks-rec-trees/data?geometry=-83.315%2C40.085%2C-82.585%2C40.177",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/137785bc78da47b4a2159f9c76218d55_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      common: "COMMON_NAME",
      location: "TREE_TYPE",
      health: "CONDITION",
      scientific: "SCIENTIFIC",
    },
  },
  {
    country: "United States",
    state: "FL",
    city: "St Augustine",
    short: "St Augustine",
    long: "St Augustine",
    id: "st_augustine",
    id_city_name: "st_augustine",
    primary: "st_augustine",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/STAUG::trees?geometry=-93.005%2C28.223%2C-69.637%2C31.556",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/8372c7d0f5a24764bd10f62f0b2f1b65_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      updated: "INSPECT_DT",
      note: "NOTES",
      scientific: "SPP",
      dbh: "DBH",
    },
  },
  {
    country: "United States",
    state: "FL",
    city: "Weston",
    short: "Weston",
    long: "Weston",
    id: "weston",
    id_city_name: "weston",
    primary: "weston",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/westonfl::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/c95f89a4db39414a89f5c29bcb6fb48d_6.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "NAME",
      genus: "GENUS",
      species: "SPECIES",
      age: "TREEAGE",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      health: "CONDITION",
      owner: "OWNEDBY",
      updated: "LASTUPDATE",
      scientific: "BOTNAME",
      family: "FAMILY",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Pacific Grove",
    short: "Pacific Grove",
    long: "Pacific Grove",
    id: "pacific_grove",
    id_city_name: "pacific_grove",
    primary: "pacific_grove",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CityPacificGrove::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/87bcc6e824214422be859b3251350829_3.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "Type",
      scientific: "BOTANICAL",
      variety: "CULTIVAR",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      condition: (x) => String(x.CONDITION).split(" - ")[0],
      comment: "NOTES",
    },
  },
  {
    country: "United States",
    state: "MT",
    city: "Bozeman",
    short: "Bozeman",
    long: "City of Bozeman",
    id: "bozeman",
    id_city_name: "bozeman",
    primary: "bozeman",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/bozeman::trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/ba0dea7927184014a8b84e64af5c7684_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      genus: "Genus",
      species: "Species",
      variety: "Cultivar",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "Condition",
      updated: "last_edited_date",
      common: "Common_Name",
      ref: "FacilityID",
    },
  },
  {
    country: "United States",
    state: "IL",
    city: "Champaign",
    short: "Champaign",
    long: "Champaign",
    id: "champaign",
    id_city_name: "champaign",
    primary: "champaign",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/cityofchampaign::city-owned-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/979bbeefffea408e8f1cb7a397196c64_22.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "ID",
      scientific: "SPP",
      common: "COMMON",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "COND",
      updated: "INSPECT_DT",
      note: "NOTES",
      family: "FAMILY",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Placentia",
    short: "Placentia",
    long: "Placentia",
    id: "placentia",
    id_city_name: "placentia",
    primary: "placentia",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/placentia::city-trees",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/8efcbe9c80ed42a29e6ad5483bd01c32_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "INVENTORYI",
      scientific: "BOTANICALN",
      common: "COMMONNAME",
      dbh: "DBH",
      height: "HEIGHT",
      updated: "EditDate",
    },
  },
  {
    country: "United States",
    state: "FL",
    city: "Sarasota",
    short: "Sarasota",
    long: "Sarasota",
    id: "sarasota",
    id_city_name: "sarasota",
    primary: "sarasota",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/sarasota::tree-inventory",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/4deeb30f44bc4b60847cf43aed1a4670_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Species",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      health: "Condition",
      owner: "Ownership",
      note: "Notes",
      updated: "last_edited_date",
    },
  },
  {
    country: "United States",
    state: "MI",
    city: "Ann Arbor",
    short: "Nichols Arboretum",
    long: "Nichols Arboretum",
    id: "nichols_arboretum",
    id_city_name: "nichols_arboretum",
    primary: "nichols_arboretum",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/umich::nichols-arboretum-inventory-survey",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/febee55e7dac43298952af77c8f8d809_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "COMMON",
      scientific: "BOTANICAL",
      variety: "CULTIVAR",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "COND",
      note: "NOTES",
      updated: "DATE",
    },
  },
  {
    country: "United States",
    state: "TX",
    city: "Denton",
    short: "UNT",
    long: "University of North Texas",
    id: "unt",
    id_city_name: "unt",
    primary: "unt",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/untgis::tree",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/ee33bf4535cd47bbb1c5661d2333d834_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: { note: "NOTES", common: "NAME_COMN", ref: "UNT_ID" },
  },
  {
    country: "United States",
    state: "CA",
    city: "Escondido",
    short: "Escondido",
    long: "City of Escondido",
    id: "escondido",
    id_city_name: "escondido",
    primary: "escondido",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CityofEscondido::tree-inventory?geometry=-122.895%2C32.313%2C-111.211%2C33.923",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/ac9caf3c7a9847b78100cc8860ddf51a_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "TREEID",
      scientific: "BOTANICAL",
      common: "COMMON",
      dbh: "DBH_RANGE",
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      health: "CONDITION",
      updated: "LAST_EDITED_DATE",
    },
  },
  {
    country: "United States",
    state: "TX",
    city: "Wylie",
    short: "Wylie",
    long: "City of Wylie",
    id: "wylie",
    id_city_name: "wylie",
    primary: "wylie",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/WylieTX::treesurvey",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/82060fffb84045fdafbe2a56c989b353_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "TK_ID",
      common: "COMMON",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      health: "CONDITION",
      updated: "INSPECT_DT",
    },
  },
  {
    country: "United States",
    state: "ME",
    city: "Auburn",
    short: "Auburn",
    long: "Auburn",
    id: "auburn",
    id_city_name: "auburn",
    primary: "auburn",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/AuburnME::treeinventory?geometry=-81.930%2C42.701%2C-58.562%2C45.462",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/91bffc476216422481b511a48796a327_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: "ID",
      common: "COMMON",
      scientific: "BOTANICAL",
      dbh: "DBH",
      health: "COND",
      note: "NOTES",
    },
  },
  {
    country: "United States",
    state: "NY",
    city: "Hudson River Park",
    short: "Hudson River Park",
    long: "Hudson River Park Trust",
    id: "hudson_river_park",
    id_city_name: "hudson_river_park",
    primary: "hudson_river_park",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/SustainableMSU::tree",
    srs: null,
    brokenDownload: true,
    download:
      "https://opendata.arcgis.com/datasets/51b5e5da030f4331af48cb052f2d2d5e_1.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "Species_Latin_Name",
      common: "Species_Common_Name",
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      structure: "Structural_Value",
      ref: "HRPT_Numbering_1",
    },
  },
  {
    country: "United States",
    state: "FL",
    city: "Cape Coral",
    short: "Cape Coral",
    long: "Cape Coral",
    id: "cape_coral",
    id_city_name: "cape_coral",
    primary: "cape_coral",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/CapeGIS::tree-inventory",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/e988fe06668e44ea996a53c4365531b9_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "SPECIES",
      dbh: "DBH",
      crown: "CANOPY",
      location: "SITE",
      health: "CONDITION",
      updated: "last_edited_date",
      heaght: "HEIGHT",
      note: "COMMENTS",
    },
  },
  {
    country: "United States",
    state: "IL",
    city: "Naperville",
    short: "Naperville",
    long: "Naperville",
    id: "naperville",
    id_city_name: "naperville",
    primary: "naperville",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/naperville::right-of-way-tree-inventory",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/51d4726531cd4ef99bfa24b99ae3ba24_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      common: "ROWTREE_TYPE",
      ref: "FACILITYID",
      health: "CONDITION_CLASS",
      updated: "DATE_CHANGED",
      planted: "DatePlanted",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      family: "FAMILY",
      variety: "CULTIVAR",
      genus: "GENUS",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Alameda",
    short: "Alameda",
    long: "Alameda",
    id: "alameda",
    id_city_name: "alameda",
    primary: "alameda",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.arboraccess.com/Custom/Alameda/Public/TreeInventoryMap.aspx?Width=1000&Height=800",
    srs: null,
    brokenDownload: false,
    download: "https://waterthetrees.com/api/csv?city=Alameda",
    format: 'csv',
    filename: 'alameda.csv',
    gdal_options: null,
    license: null,
    email: "pw@alamedaca.gov",
    contact: "Erin Smith",
    crosswalk: {
      common: 'common',
      ref: "idReference",
      health: "health",
      height: "height",
      address: "address",
      planted: "datePlanted",
      dbh: "dbh",
      family: 'scientific'.split(' ')[0],
      species: 'scientific',
      genus: 'genus',
      owner: "owner",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "Oakland",
    short: "Oakland",
    long: "Oakland",
    id: "oakland",
    id_city_name: "oakland",
    primary: "oakland",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://www.arboraccess.com/Custom/Alameda/Public/TreeInventoryMap.aspx?Width=1000&Height=800",
    srs: null,
    brokenDownload: false,
    download: "https://waterthetrees.com/api/csv?city=Oakland",
    format: 'csv',
    filename: 'oakland.csv',
    gdal_options: null,
    license: null,
    email: "sctreeplanting@gmail.com",
    contact: "Bart Wright",
    crosswalk: {
      common: 'common',
      ref: "idReference",
      health: "health",
      address: "address",
      planted: "datePlanted",
      dbh: "dbh",
      height: "height",
      family: (x) => x.scientific.split(' ')[0],
      genus: 'genus',
      species: 'scientific',
      scientific: 'scientific',
      owner: "owner",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "San Francisco",
    short: "San Francisco",
    long: "San Francisco",
    id: "san_francisco",
    id_city_name: "san_francisco",
    primary: "san_francisco",
    center: null,
    latitude: null,
    longitude: null,
    info: "https://data.sfgov.org/City-Infrastructure/Street-Tree-List/tkzw-k3nq",
    srs: null,
    brokenDownload: false,
    download:
      "https://data.sfgov.org/api/views/tkzw-k3nq/rows.csv?accessType=DOWNLOAD",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      ref: 'TreeID',
      health: 'CONDITION_CLASS',
      updated: 'DATE_CHANGED',
      address: 'qAddress',
      planted: 'PlantDate',
      dbh: 'DBH',
      family: (x) => x.qSpecies.split(' :: ')[0],
      variety: 'qSpecies',
      species: (x) => x.qSpecies.split(' :: ')[0],
      genus: (x) => x.qSpecies.split(' :: ')[0].split(' ')[0],
      common: (x) => x.qSpecies.split(' :: ')[1],
      scientific: (x) => x.qSpecies.split(' :: ')[0],
      owner: 'qLegalStatus',
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "San Jose",
    short: "San Jose",
    long: "San Jose Medians and Backups",
    id: "san_jose1",
    id_city_name: "san_jose1",
    primary: "san_jose1",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/csjdotgis::trees-medians-and-backups",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/0b0ad30145394b1588ff09ef1a7c9225_1.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "NAMESCIENTIFIC",
      age: "TREEAGE",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      crown: (x) => numeric(Number(tree[x]) / 3.280084),
      health: (x) => String(x.CONDITION).split(" ")[0],
      note: "NOTES",
      updated: "EditDate",
      owner: "OWNEDBY",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "San Jose",
    short: "San Jose",
    long: "San Jose Special Districts",
    id: "san_jose2",
    id_city_name: "san_jose2",
    primary: "san_jose1",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/csjdotgis::trees-special-districts",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/0b0ad30145394b1588ff09ef1a7c9225_0.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "NAMESCIENTIFIC",
      age: "TREEAGE",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      crown: (x) => numeric(Number(tree[x]) / 3.280084),
      health: (x) => String(x.CONDITION).split(" ")[0],
      note: "NOTES",
      updated: "EditDate",
      owner: "OWNEDBY",
    },
  },
  {
    country: "United States",
    state: "CA",
    city: "San Jose",
    short: "San Jose",
    long: "San Jose General Fund",
    id: "san_jose3",
    id_city_name: "san_jose3",
    primary: "san_jose1",
    center: null,
    latitude: null,
    longitude: null,
    info: "http://hub.arcgis.com/datasets/csjdotgis::trees-general-fund-street",
    srs: null,
    brokenDownload: false,
    download:
      "https://opendata.arcgis.com/datasets/0b0ad30145394b1588ff09ef1a7c9225_2.csv",
    format: null,
    filename: null,
    gdal_options: null,
    license: null,
    email: null,
    contact: null,
    crosswalk: {
      scientific: "NAMESCIENTIFIC",
      age: "TREEAGE",
      dbh: (x) => numeric(Number(tree[x]) * 2.54),
      height: (x) => numeric(Number(tree[x]) / 3.280084),
      crown: (x) => numeric(Number(tree[x]) / 3.280084),
      health: (x) => String(x.CONDITION).split(" ")[0],
      note: "NOTES",
      updated: "EditDate",
      owner: "OWNEDBY",
    },
  },
];
